-- Create table for storing Google Calendar tokens
CREATE TABLE IF NOT EXISTS saas_integracoes_google (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    access_token TEXT NOT NULL,
    refresh_token TEXT,
    expiry_date BIGINT,
    scope TEXT,
    token_type TEXT,
    calendar_id TEXT DEFAULT 'primary',
    watch_channel_id TEXT,
    watch_resource_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_user_integration UNIQUE (user_id)
);

-- Enable RLS
ALTER TABLE saas_integracoes_google ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see/edit their own tokens
CREATE POLICY "Users can manage their own google tokens" ON saas_integracoes_google
    FOR ALL
    USING (auth.uid() = user_id);

-- Add google_event_id to agendamentos table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'agendamentos'
        AND column_name = 'google_event_id'
    ) THEN
        ALTER TABLE agendamentos ADD COLUMN google_event_id TEXT;
        CREATE INDEX idx_agendamentos_google_event_id ON agendamentos(google_event_id);
    END IF;
END $$;
