-- Create salas_recursos table
CREATE TABLE IF NOT EXISTS salas_recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    cor_hex TEXT DEFAULT '#3B82F6',
    icone TEXT DEFAULT 'box',
    capacidade INTEGER DEFAULT 1,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE
);

-- Enable RLS
ALTER TABLE salas_recursos ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow all for authenticated" ON salas_recursos;
CREATE POLICY "Allow all for authenticated" ON salas_recursos FOR ALL USING (auth.role() = 'authenticated');
