-- Create recursos table (if not exists, as requested)
CREATE TABLE IF NOT EXISTS recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    nome_item TEXT NOT NULL,
    foto_url TEXT,
    localizacao TEXT,
    quantidade INTEGER DEFAULT 1,
    objetivos_terapeuticos TEXT[],
    status_conservacao TEXT CHECK (status_conservacao IN ('Excelente', 'Bom', 'Necessita reparo', 'Fora de uso')) DEFAULT 'Excelente'
);

-- Enable RLS
ALTER TABLE recursos ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow all for authenticated" ON recursos;
CREATE POLICY "Allow all for authenticated" ON recursos FOR ALL USING (auth.role() = 'authenticated');

-- Storage Bucket for recursos
INSERT INTO storage.buckets (id, name, public) VALUES ('recursos', 'recursos', true) ON CONFLICT DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Recursos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Recursos" ON storage.objects;

CREATE POLICY "Public Recursos" ON storage.objects FOR SELECT USING (bucket_id = 'recursos');
CREATE POLICY "Authenticated Upload Recursos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'recursos' AND auth.role() = 'authenticated');
