-- Drop table if exists to ensure clean slate
DROP TABLE IF EXISTS agendamentos CASCADE;

-- Create agendamentos table
CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    id_sala BIGINT REFERENCES salas_recursos(id) ON DELETE SET NULL,
    data_hora_inicio TIMESTAMPTZ NOT NULL,
    data_hora_fim TIMESTAMPTZ NOT NULL,
    tipo_sessao TEXT DEFAULT 'individual', -- individual, dupla, avaliacao
    status TEXT DEFAULT 'agendado', -- agendado, realizado, cancelado, falta
    observacoes TEXT
);

-- Enable RLS
ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS "Allow all for authenticated" ON agendamentos;
CREATE POLICY "Allow all for authenticated" ON agendamentos FOR ALL USING (auth.role() = 'authenticated');
