-- Create prompts_ia table
create table if not exists prompts_ia (
  id bigint generated by default as identity primary key,
  id_clinica bigint references saas_clinicas(id) on delete cascade, -- Assuming table name is 'clinicas' based on previous context, user said 'saas_clinicas' but usually it's 'clinicas' in this project. I will check.
  nome_prompt text not null,
  descricao text,
  prompt_texto text not null,
  modelo_gemini text default 'gemini-2.5-flash',
  temperatura decimal default 0.7,
  ativo boolean default true,
  criado_por uuid references usuarios(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(id_clinica, nome_prompt)
);

-- Create planos_intervencao_ia table
create table if not exists planos_intervencao_ia (
  id bigint generated by default as identity primary key,
  id_paciente bigint references pacientes(id),
  id_prompt_ia bigint references prompts_ia(id),
  id_terapeuta uuid references usuarios(id),
  plano_original text,
  plano_final text,
  recursos_sugeridos jsonb,
  created_at timestamptz default now()
);

-- Add RLS Policies
alter table prompts_ia enable row level security;
alter table planos_intervencao_ia enable row level security;

-- Policies for prompts_ia
create policy "Users can view prompts from their clinic"
  on prompts_ia for select
  using (id_clinica in (
    select id_clinica from usuarios where id = auth.uid()
  ));

create policy "Admins can insert/update/delete prompts"
  on prompts_ia for all
  using (
    id_clinica in (
      select id_clinica from usuarios where id = auth.uid() and (tipo_perfil = 'admin_clinica' or tipo_perfil = 'master_admin')
    )
  );

-- Policies for planos_intervencao_ia
create policy "Users can view/insert plans for their clinic's patients"
  on planos_intervencao_ia for all
  using (
    id_paciente in (
      select id from pacientes where id_clinica in (
        select id_clinica from usuarios where id = auth.uid()
      )
    )
  );

-- Insert default prompt (Need to handle id_clinica dynamically or just insert for a specific one if known, but user asked to insert. I'll make a function or just leave it for the app logic to seed, but user asked to execute. I will try to insert for clinic 1 if it exists, or user can run it manually).
-- I will skip the specific insert with fixed ID 1 to avoid errors if ID 1 doesn't exist, but I will include the SQL for it as requested, wrapped in a block.

do $$
begin
  if exists (select 1 from saas_clinicas where id = 1) then
    insert into prompts_ia (id_clinica, nome_prompt, descricao, prompt_texto, criado_por)
    values 
    (1, 'Dra. Clara – Plano Completo 50min', 'Plano detalhado e carinhoso para crianças no espectro', 
    'Você é a Dra. Clara, musicoterapeuta com 22 anos de experiência em TEA e neurodesenvolvimento.

Paciente: {{NOME}} – {{IDADE}} anos
Diagnóstico e características: {{DIAGNOSTICO_E_ANAMNESE}}
Preferências musicais e hiperfocos: {{PREFERENCIAS}}
Sensibilidades atuais: {{SENSIBILIDADES}}
Relatórios das últimas sessões: {{ULTIMAS_SESSOES}}
Recursos disponíveis na clínica: {{RECURSOS_LISTA}}
Salas disponíveis: {{SALAS_LISTA}}

Crie UM plano de intervenção de 50 minutos para a próxima sessão em markdown bonito e estruturado:
## Objetivo principal
## Objetivos secundários  
## Materiais necessários (use APENAS os que estão na lista acima)
## Sala sugerida
## Sequência de atividades (com duração exata)
## Estratégias de regulação sensorial
## Música recomendada (nome da música + BPM + justificativa)
## Fechamento carinhoso para o responsável

Seja extremamente prática, afetiva e precisa.', null)
    on conflict do nothing;
  end if;
end $$;
