-- CRITICAL: Add missing email column to usuarios table
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';

-- Update constraint to ensure email is unique
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_email_key;
ALTER TABLE usuarios ADD CONSTRAINT usuarios_email_key UNIQUE (email);

-- Add missing columns to saas_clinicas
ALTER TABLE saas_clinicas 
ADD COLUMN IF NOT EXISTS max_terapeutas INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS logo_url TEXT;

-- Ensure usuarios table has all columns
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS nome TEXT NOT NULL DEFAULT '';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS celular TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cpf TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS tipo_perfil TEXT;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS id_clinica BIGINT REFERENCES saas_clinicas(id);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS foto_url TEXT;

-- Add constraint for tipo_perfil if not exists
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'usuarios_tipo_perfil_check'
    ) THEN
        ALTER TABLE usuarios ADD CONSTRAINT usuarios_tipo_perfil_check 
        CHECK (tipo_perfil IN ('master_admin', 'admin_clinica', 'terapeuta', 'responsavel'));
    END IF;
END $$;

-- Create terapeutas_curriculo
CREATE TABLE IF NOT EXISTS terapeutas_curriculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    registro_profissional TEXT,
    formacao TEXT,
    especialidades TEXT[],
    publico_alvo TEXT[],
    bio TEXT
);

-- Ensure all columns exist in terapeutas_curriculo
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE;
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS registro_profissional TEXT;
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS formacao TEXT;
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS especialidades TEXT[];
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS publico_alvo TEXT[];
ALTER TABLE terapeutas_curriculo ADD COLUMN IF NOT EXISTS bio TEXT;

-- Create pacientes
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    clinica_id BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    data_nascimento DATE NOT NULL,
    foto_url TEXT,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE
);

-- Create responsaveis
CREATE TABLE IF NOT EXISTS responsaveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    email TEXT,
    user_id UUID REFERENCES auth.users(id)
);

-- Create pacientes_responsaveis (Many-to-Many)
CREATE TABLE IF NOT EXISTS pacientes_responsaveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES responsaveis(id) ON DELETE CASCADE,
    grau_parentesco TEXT NOT NULL,
    responsavel_principal BOOLEAN DEFAULT FALSE
);

-- Create pacientes_anamnese
CREATE TABLE IF NOT EXISTS pacientes_anamnese (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    gestacao_intercorrencias TEXT,
    parto_tipo TEXT,
    desenvolvimento_motor TEXT,
    desenvolvimento_linguagem TEXT,
    historico_medico TEXT,
    medicamentos_atuais TEXT,
    alergias TEXT,
    laudo_medico_arquivo_url TEXT,
    laudo_medico_data_upload TIMESTAMPTZ,
    diagnostico_principal TEXT,
    musicoterapia JSONB
);

-- Create pacientes_terapeutas (Many-to-Many)
CREATE TABLE IF NOT EXISTS pacientes_terapeutas (
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    terapeuta_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (paciente_id, terapeuta_id)
);

-- RLS Policies
ALTER TABLE saas_clinicas ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE terapeutas_curriculo ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsaveis ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes_responsaveis ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes_anamnese ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes_terapeutas ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Allow all for authenticated" ON saas_clinicas;
DROP POLICY IF EXISTS "Allow all for authenticated" ON usuarios;
DROP POLICY IF EXISTS "Allow all for authenticated" ON terapeutas_curriculo;
DROP POLICY IF EXISTS "Allow all for authenticated" ON pacientes;
DROP POLICY IF EXISTS "Allow all for authenticated" ON responsaveis;
DROP POLICY IF EXISTS "Allow all for authenticated" ON pacientes_responsaveis;
DROP POLICY IF EXISTS "Allow all for authenticated" ON pacientes_anamnese;
DROP POLICY IF EXISTS "Allow all for authenticated" ON pacientes_terapeutas;

-- Allow everything for authenticated users for now (to be refined)
CREATE POLICY "Allow all for authenticated" ON saas_clinicas FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON usuarios FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON terapeutas_curriculo FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON pacientes FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON responsaveis FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON pacientes_responsaveis FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON pacientes_anamnese FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Allow all for authenticated" ON pacientes_terapeutas FOR ALL USING (auth.role() = 'authenticated');

-- Storage Buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('logos', 'logos', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('laudos', 'laudos', false) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('terapeutas-fotos', 'terapeutas-fotos', true) ON CONFLICT DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('clinicas-logos', 'clinicas-logos', true) ON CONFLICT DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Logos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Logos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Laudos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Read Laudos" ON storage.objects;
DROP POLICY IF EXISTS "Public Terapeutas Fotos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Terapeutas Fotos" ON storage.objects;
DROP POLICY IF EXISTS "Public Clinicas Logos" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Clinicas Logos" ON storage.objects;

CREATE POLICY "Public Logos" ON storage.objects FOR SELECT USING (bucket_id = 'logos');
CREATE POLICY "Authenticated Upload Logos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'logos' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated Upload Laudos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'laudos' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated Read Laudos" ON storage.objects FOR SELECT USING (bucket_id = 'laudos' AND auth.role() = 'authenticated');
CREATE POLICY "Public Terapeutas Fotos" ON storage.objects FOR SELECT USING (bucket_id = 'terapeutas-fotos');
CREATE POLICY "Authenticated Upload Terapeutas Fotos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'terapeutas-fotos' AND auth.role() = 'authenticated');
CREATE POLICY "Public Clinicas Logos" ON storage.objects FOR SELECT USING (bucket_id = 'clinicas-logos');
CREATE POLICY "Authenticated Upload Clinicas Logos" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'clinicas-logos' AND auth.role() = 'authenticated');
