-- ============================================================================
-- TIRILO SAAS - SCHEMA COMPLETO DO BANCO DE DADOS
-- ============================================================================
-- Descrição: Schema consolidado de todas as tabelas do sistema Tirilo
-- Versão: 1.2.0
-- Data: 04/12/2024
-- 
-- IMPORTANTE: Este arquivo representa o estado FINAL do banco de dados.
-- Use este arquivo para:
--   1. Documentação do schema
--   2. Criar banco de dados em novo servidor
--   3. Referência para desenvolvimento
-- 
-- Ordem de execução:
--   1. Tabelas principais (sem dependências)
--   2. Tabelas com foreign keys
--   3. Políticas RLS
--   4. Storage buckets e políticas
-- ============================================================================

-- ============================================================================
-- 1. TABELAS PRINCIPAIS (SEM DEPENDÊNCIAS)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: saas_clinicas
-- Descrição: Armazena informações das clínicas cadastradas no SaaS
-- Acesso: Apenas Super Admin (master)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saas_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia TEXT NOT NULL,                    -- Nome comercial da clínica
    razao_social TEXT NOT NULL,                     -- Razão social (CNPJ)
    cnpj TEXT,                                       -- CNPJ da clínica
    telefone TEXT,                                   -- Telefone principal
    email TEXT,                                      -- Email de contato
    endereco TEXT,                                   -- Endereço completo
    cidade TEXT,                                     -- Cidade
    estado TEXT,                                     -- Estado (UF)
    cep TEXT,                                        -- CEP
    logo_url TEXT,                                   -- URL do logo no storage
    config_cor_primaria TEXT DEFAULT '#3b82f6',     -- Cor primária da marca
    ativa BOOLEAN DEFAULT TRUE,                      -- Status da clínica
    max_terapeutas INTEGER DEFAULT 5,                -- Limite de terapeutas
    max_pacientes INTEGER DEFAULT 50,                -- Limite de pacientes
    plano TEXT DEFAULT 'basico',                     -- Plano contratado
    data_vencimento TIMESTAMP WITH TIME ZONE,        -- Vencimento do plano
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Apenas Super Admin pode acessar
ALTER TABLE saas_clinicas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super Admin can view all clinics" ON saas_clinicas
FOR SELECT USING (true);

CREATE POLICY "Super Admin can insert clinics" ON saas_clinicas
FOR INSERT WITH CHECK (true);

CREATE POLICY "Super Admin can update clinics" ON saas_clinicas
FOR UPDATE USING (true);

-- ============================================================================
-- 2. TABELAS DE USUÁRIOS E AUTENTICAÇÃO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: usuarios
-- Descrição: Usuários do sistema (Gestores, Terapeutas, Recepcionistas)
-- Nota: Super Admin NÃO tem registro aqui (identificado por ausência de id_clinica)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,                      -- Email de login
    nome_completo TEXT NOT NULL,                     -- Nome completo do usuário
    apelido TEXT,                                    -- Nome curto/apelido (ex: "Dr. João", "Mari")
    tipo_perfil TEXT NOT NULL CHECK (tipo_perfil IN ('admin', 'terapeuta', 'recepcao', 'financeiro')),
    celular_whatsapp TEXT,                           -- Telefone/WhatsApp
    foto_url TEXT,                                   -- URL da foto de perfil
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do usuário (soft delete)
    precisa_trocar_senha BOOLEAN DEFAULT TRUE,       -- Flag para primeiro acesso
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Usuários veem apenas da sua clínica
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_authenticated" ON usuarios
FOR SELECT TO authenticated USING (true);

CREATE POLICY "allow_update_own_profile" ON usuarios
FOR UPDATE USING (id = auth.uid());

CREATE POLICY "allow_insert_admin" ON usuarios
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM usuarios u 
        WHERE u.id = auth.uid() 
        AND u.tipo_perfil = 'admin' 
        AND u.id_clinica = usuarios.id_clinica
    )
);

-- ----------------------------------------------------------------------------
-- TABELA: terapeutas_curriculo
-- Descrição: Currículo e informações profissionais dos terapeutas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS terapeutas_curriculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    registro_profissional TEXT,                      -- CRP, CRM, etc.
    especialidades TEXT[],                           -- Array de especialidades
    formacao_academica TEXT,                         -- Graduação, pós, etc.
    experiencia_anos INTEGER,                        -- Anos de experiência
    bio TEXT,                                        -- Biografia profissional
    curriculo_url TEXT,                              -- URL do currículo em PDF
    valor_hora_padrao DECIMAL(10,2),                 -- Valor base por hora/sessão
    porcentagem_repasse DECIMAL(5,2),                -- Porcentagem de repasse (0-100)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE terapeutas_curriculo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_curriculo" ON terapeutas_curriculo
FOR SELECT USING (
    id_usuario = auth.uid() 
    OR 
    EXISTS (
        SELECT 1 FROM usuarios 
        WHERE id = auth.uid() 
        AND tipo_perfil IN ('admin', 'financeiro')
    )
);

CREATE POLICY "allow_update_curriculo" ON terapeutas_curriculo
FOR UPDATE USING (
    id_usuario = auth.uid() 
    OR 
    EXISTS (
        SELECT 1 FROM usuarios 
        WHERE id = auth.uid() 
        AND tipo_perfil IN ('admin', 'financeiro')
    )
);

CREATE POLICY "allow_insert_curriculo" ON terapeutas_curriculo
FOR INSERT WITH CHECK (
    id_usuario = auth.uid() 
    OR 
    EXISTS (
        SELECT 1 FROM usuarios 
        WHERE id = auth.uid() 
        AND tipo_perfil IN ('admin', 'financeiro')
    )
);

-- ============================================================================
-- 3. TABELAS DE PACIENTES E RESPONSÁVEIS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: responsaveis
-- Descrição: Responsáveis pelos pacientes (pais, tutores)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS responsaveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome_completo TEXT NOT NULL,                     -- Nome do responsável
    cpf TEXT,                                        -- CPF
    email TEXT,                                      -- Email
    telefone TEXT,                                   -- Telefone principal
    celular_whatsapp TEXT,                           -- WhatsApp
    endereco TEXT,                                   -- Endereço completo
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    parentesco TEXT,                                 -- Relação com o paciente
    profissao TEXT,                                  -- Profissão
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE responsaveis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view responsaveis from their clinic" ON responsaveis
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: pacientes
-- Descrição: Pacientes atendidos na clínica
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE SET NULL,
    nome TEXT NOT NULL,                              -- Nome do paciente
    data_nascimento DATE,                            -- Data de nascimento
    cpf TEXT,                                        -- CPF (se aplicável)
    sexo TEXT CHECK (sexo IN ('M', 'F', 'Outro')),  -- Sexo
    foto_url TEXT,                                   -- Foto do paciente
    telefone TEXT,                                   -- Telefone (se tiver)
    email TEXT,                                      -- Email (se tiver)
    endereco TEXT,                                   -- Endereço
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    escola TEXT,                                     -- Escola que frequenta
    serie_ano TEXT,                                  -- Série/Ano escolar
    turno_escolar TEXT,                              -- Manhã, Tarde, Integral
    observacoes TEXT,                                -- Observações gerais
    valor_sessao_padrao DECIMAL(10,2),               -- Valor padrão por sessão (fallback)
    dia_vencimento_padrao INTEGER,                   -- Dia de vencimento preferencial
    convenio_nome TEXT,                              -- Nome do convênio (ex: Unimed)
    convenio_numero_carteirinha TEXT,                -- Número da carteirinha do convênio
    convenio_validade DATE,                          -- Validade da carteirinha
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do paciente
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "isolate_by_clinic_select" ON pacientes
FOR SELECT USING (
    id_clinica = get_my_clinic_id()
);

CREATE POLICY "isolate_by_clinic_insert" ON pacientes
FOR INSERT WITH CHECK (
    id_clinica = get_my_clinic_id()
);

CREATE POLICY "isolate_by_clinic_update" ON pacientes
FOR UPDATE USING (
    id_clinica = get_my_clinic_id()
);

CREATE POLICY "isolate_by_clinic_delete" ON pacientes
FOR DELETE USING (
    id_clinica = get_my_clinic_id()
);

-- ----------------------------------------------------------------------------
-- TABELA: pacientes_terapeutas
-- Descrição: Relacionamento N:N entre pacientes e terapeutas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pacientes_terapeutas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    terapeuta_id UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    data_inicio DATE DEFAULT CURRENT_DATE,           -- Início do acompanhamento
    data_fim DATE,                                   -- Fim do acompanhamento
    ativo BOOLEAN DEFAULT TRUE,                      -- Relacionamento ativo
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(paciente_id, terapeuta_id)
);

ALTER TABLE pacientes_terapeutas ENABLE ROW LEVEL SECURITY;

-- Função auxiliar para obter o ID da clínica do usuário atual
CREATE OR REPLACE FUNCTION get_my_clinic_id()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT id_clinica FROM usuarios WHERE id = auth.uid();
$$;

CREATE POLICY "isolate_relationships_select" ON pacientes_terapeutas
FOR SELECT USING (
    paciente_id IN (SELECT id FROM pacientes)
);

CREATE POLICY "isolate_relationships_insert" ON pacientes_terapeutas
FOR INSERT WITH CHECK (
    paciente_id IN (SELECT id FROM pacientes)
);

CREATE POLICY "isolate_relationships_delete" ON pacientes_terapeutas
FOR DELETE USING (
    paciente_id IN (SELECT id FROM pacientes)
);

-- ----------------------------------------------------------------------------
-- TABELA: anamnese
-- Descrição: Anamnese e histórico clínico dos pacientes
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pacientes_anamnese (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL UNIQUE,
    queixa_principal TEXT,                           -- Motivo da consulta
    historico_familiar TEXT,                         -- Histórico familiar
    historico_gestacional TEXT,                      -- Gestação e parto
    desenvolvimento_motor TEXT,                      -- Desenvolvimento motor
    desenvolvimento_linguagem TEXT,                  -- Desenvolvimento da linguagem
    historico_escolar TEXT,                          -- Histórico escolar
    medicamentos_uso TEXT,                           -- Medicamentos em uso
    alergias TEXT,                                   -- Alergias
    diagnosticos_previos TEXT,                       -- Diagnósticos anteriores
    laudo_medico_arquivo_url TEXT,                   -- Path do laudo no storage
    observacoes_clinicas TEXT,                       -- Observações do terapeuta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE pacientes_anamnese ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view anamnese from their clinic" ON pacientes_anamnese
FOR SELECT USING (
    id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid()))
);

-- ============================================================================
-- 4. TABELAS DE AGENDAMENTOS E SALAS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: salas
-- Descrição: Salas de atendimento da clínica
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS salas_recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,                              -- Nome da sala (ex: "Sala 1")
    descricao TEXT,                                  -- Descrição da sala
    capacidade INT DEFAULT 1,                        -- Capacidade de pessoas
    cor_identificacao TEXT DEFAULT '#3b82f6',        -- Cor para identificação visual
    foto_url TEXT,                                   -- URL da foto da sala (Supabase Storage)
    ativa BOOLEAN DEFAULT TRUE,                      -- Status da sala
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE salas_recursos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view salas from their clinic" ON salas_recursos
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: agendamentos
-- Descrição: Agendamentos de sessões
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    id_sala BIGINT REFERENCES salas(id) ON DELETE SET NULL,
    data_hora_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_hora_fim TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'agendado' CHECK (status IN ('agendado', 'em_andamento', 'concluido', 'cancelado')),
    tipo_sessao TEXT,                                -- Tipo de sessão (avaliação, terapia, etc.)
    observacoes TEXT,                                -- Observações do agendamento
    id_lancamento_financeiro BIGINT REFERENCES financeiro_lancamentos(id) ON DELETE SET NULL, -- Vínculo com cobrança
    valor_sessao DECIMAL(10,2),                      -- Valor cobrado nesta sessão
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view agendamentos from their clinic" ON agendamentos
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ============================================================================
-- 5. TABELAS DE RELATÓRIOS E EVOLUÇÃO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: relatorios
-- Descrição: Relatórios e evoluções das sessões
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS relatorios_atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL NOT NULL,
    id_agendamento BIGINT REFERENCES agendamentos(id) ON DELETE SET NULL,
    data_sessao DATE NOT NULL,                       -- Data da sessão
    tipo_relatorio TEXT DEFAULT 'evolucao',          -- Tipo (evolução, avaliação, etc.)
    titulo TEXT,                                     -- Título do relatório
    conteudo TEXT NOT NULL,                          -- Conteúdo do relatório
    objetivos TEXT,                                  -- Objetivos trabalhados
    atividades TEXT,                                 -- Atividades realizadas
    observacoes TEXT,                                -- Observações
    anexos_urls TEXT[],                              -- URLs de anexos
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE relatorios_atendimento ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Therapists can view their own reports" ON relatorios_atendimento
FOR SELECT USING (
    id_terapeuta = auth.uid()
    OR id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin'))
);

-- ============================================================================
-- 6. TABELAS DE ASSISTENTE IA
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: prompts_ia
-- Descrição: Prompts customizados para o assistente de IA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prompts_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    terapeuta_id UUID REFERENCES usuarios(id) NOT NULL, -- Renomeado de id_terapeuta (legacy)
    nome TEXT NOT NULL,                              -- Nome do prompt
    descricao TEXT,                                  -- Descrição do prompt
    prompt_texto TEXT NOT NULL,                      -- Texto do prompt
    categoria TEXT,                                  -- Categoria (plano, relatório, etc.)
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do prompt
    criado_por UUID,                                 -- Campo legado para migração
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT prompts_ia_unique_owner_name UNIQUE (id_clinica, terapeuta_id, nome_prompt) -- Unicidade por terapeuta
);

ALTER TABLE prompts_ia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view prompts from their clinic" ON prompts_ia
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: planos_ia
-- Descrição: Planos de intervenção gerados pela IA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS planos_intervencao_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL NOT NULL,
    id_prompt BIGINT REFERENCES prompts_ia(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,                            -- Título do plano
    conteudo_gerado TEXT NOT NULL,                   -- Plano gerado pela IA
    modelo_ia TEXT DEFAULT 'gemini-2.0-flash-exp',  -- Modelo usado
    prompt_usado TEXT,                               -- Prompt que foi usado
    aprovado BOOLEAN DEFAULT FALSE,                  -- Se foi aprovado pelo terapeuta
    data_aprovacao TIMESTAMP WITH TIME ZONE,         -- Data de aprovação
    observacoes TEXT,                                -- Observações do terapeuta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE planos_intervencao_ia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Therapists can view their own AI plans" ON planos_intervencao_ia
FOR SELECT USING (
    id_terapeuta = auth.uid()
    OR id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin'))
);

-- ============================================================================
-- 7. TABELAS DE HELP DESK (SUPORTE)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: help_desk_tickets
-- Descrição: Tickets de suporte abertos pelas clínicas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS help_desk_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    id_usuario_criador UUID NOT NULL,                -- Pode ser NULL se Super Admin
    assunto TEXT NOT NULL,                           -- Assunto do chamado
    tipo TEXT DEFAULT 'duvida' CHECK (tipo IN ('problema', 'sugestao', 'duvida', 'financeiro', 'outro')),
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_andamento', 'aguardando_cliente', 'resolvido', 'fechado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE help_desk_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tickets" ON help_desk_tickets
FOR SELECT USING (
    id_usuario_criador = auth.uid()
    OR id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    OR auth.uid() IN (SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'master_admin')
);

-- ----------------------------------------------------------------------------
-- TABELA: help_desk_mensagens
-- Descrição: Mensagens dos tickets de suporte
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS help_desk_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket BIGINT REFERENCES help_desk_tickets(id) ON DELETE CASCADE NOT NULL,
    id_usuario UUID,                                 -- NULL se for Super Admin
    mensagem TEXT NOT NULL,                          -- Conteúdo da mensagem
    anexo_url TEXT,                                  -- Path do anexo no storage
    anexo_nome TEXT,                                 -- Nome original do arquivo
    anexo_tipo TEXT,                                 -- MIME type do arquivo
    lida BOOLEAN DEFAULT FALSE,                      -- Se foi lida
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE help_desk_mensagens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view messages from their tickets" ON help_desk_mensagens
FOR SELECT USING (
    id_ticket IN (SELECT id FROM help_desk_tickets WHERE id_usuario_criador = auth.uid() OR id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid()))
);

-- ============================================================================
-- 8. TABELAS DE MATERIAIS E RECURSOS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: materiais
-- Descrição: Materiais e recursos terapêuticos
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,                              -- Nome do material
    descricao TEXT,                                  -- Descrição
    categoria TEXT,                                  -- Categoria (jogo, livro, etc.)
    quantidade INTEGER DEFAULT 1,                    -- Quantidade disponível
    localizacao TEXT,                                -- Onde está guardado
    foto_url TEXT,                                   -- Foto do material
    disponivel BOOLEAN DEFAULT TRUE,                 -- Se está disponível
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE recursos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view materiais from their clinic" ON recursos
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ============================================================================
-- 9. STORAGE BUCKETS E POLÍTICAS
-- ============================================================================

-- Bucket: laudos (privado)
-- Descrição: Laudos médicos dos pacientes
INSERT INTO storage.buckets (id, name, public)
VALUES ('laudos', 'laudos', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Users can upload laudos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'laudos'
    AND auth.uid() IS NOT NULL
);

CREATE POLICY "Users can view laudos from their clinic" ON storage.objects
FOR SELECT USING (
    bucket_id = 'laudos'
    AND auth.uid() IS NOT NULL
);

-- Bucket: help-desk-anexos (privado)
-- Descrição: Anexos dos tickets de suporte
INSERT INTO storage.buckets (id, name, public)
VALUES ('help-desk-anexos', 'help-desk-anexos', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Users can upload help desk attachments" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'help-desk-anexos'
    AND auth.uid() IS NOT NULL
);

CREATE POLICY "Users can view help desk attachments" ON storage.objects
FOR SELECT USING (
    bucket_id = 'help-desk-anexos'
    AND auth.uid() IS NOT NULL
);

-- Bucket: logos (público)
-- Descrição: Logos das clínicas
INSERT INTO storage.buckets (id, name, public)
VALUES ('logos', 'logos', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Anyone can view logos" ON storage.objects
FOR SELECT USING (bucket_id = 'logos');

CREATE POLICY "Admins can upload logos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'logos'
    AND auth.uid() IS NOT NULL
);


-- Bucket: fotos (público)
-- Descrição: Fotos de salas e materiais
INSERT INTO storage.buckets (id, name, public)
VALUES ('fotos', 'fotos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Permitir visualização pública
CREATE POLICY "Anyone can view fotos" ON storage.objects
FOR SELECT USING (bucket_id = 'fotos');

-- Permitir upload para usuários autenticados
CREATE POLICY "Users can upload fotos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- Permitir atualização para usuários autenticados
CREATE POLICY "Users can update fotos" ON storage.objects
FOR UPDATE USING (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- Permitir exclusão para usuários autenticados
CREATE POLICY "Users can delete fotos" ON storage.objects
FOR DELETE USING (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- ============================================================================
-- 10. ÍNDICES PARA PERFORMANCE
-- ============================================================================

-- Índices para melhorar performance de queries frequentes
CREATE INDEX IF NOT EXISTS idx_usuarios_id_clinica ON usuarios(id_clinica);
CREATE INDEX IF NOT EXISTS idx_usuarios_tipo_perfil ON usuarios(tipo_perfil);
CREATE INDEX IF NOT EXISTS idx_pacientes_id_clinica ON pacientes(id_clinica);
CREATE INDEX IF NOT EXISTS idx_pacientes_id_responsavel ON pacientes(id_responsavel);
CREATE INDEX IF NOT EXISTS idx_agendamentos_id_clinica ON agendamentos(id_clinica);
CREATE INDEX IF NOT EXISTS idx_agendamentos_id_terapeuta ON agendamentos(id_terapeuta);
CREATE INDEX IF NOT EXISTS idx_agendamentos_data_hora_inicio ON agendamentos(data_hora_inicio);
CREATE INDEX IF NOT EXISTS idx_help_desk_tickets_id_clinica ON help_desk_tickets(id_clinica);
CREATE INDEX IF NOT EXISTS idx_help_desk_mensagens_id_ticket ON help_desk_mensagens(id_ticket);

-- ============================================================================
-- 11. TABELAS DE FINANCEIRO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: contratos
-- Descrição: Contratos financeiros com responsáveis
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL, -- Adicionado na version 1.3.1
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE CASCADE NOT NULL,
    tipo_cobranca TEXT NOT NULL CHECK (tipo_cobranca IN ('por_sessao', 'mensal_fixo')),
    valor DECIMAL(10,2) NOT NULL, -- Valor da sessão ou valor mensal
    data_inicio DATE NOT NULL,
    data_fim DATE,
    dia_vencimento INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'ativo' CHECK (status IN ('ativo', 'cancelado', 'finalizado')),
    arquivo_url TEXT, -- URL do PDF no bucket
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE contratos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to contracts" ON contratos
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND (
        -- Admins e Financeiro veem tudo
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'financeiro', 'super_admin'))
        OR 
        -- Terapeutas veem seus próprios contratos OU se a política da clínica permitir
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'terapeuta')
    )
);

-- ----------------------------------------------------------------------------
-- TABELA: financeiro_categorias
-- Descrição: Categorias de receitas e despesas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS financeiro_categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE financeiro_categorias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to financial categories" ON financeiro_categorias
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND (
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'financeiro'))
    )
);

-- ----------------------------------------------------------------------------
-- TABELA: financeiro_lancamentos
-- Descrição: Lançamentos financeiros (Receitas e Despesas)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS financeiro_lancamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    descricao TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    status TEXT DEFAULT 'pendente' CHECK (status IN ('pendente', 'pago', 'cancelado')),
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE SET NULL,
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE SET NULL,
    id_categoria BIGINT REFERENCES financeiro_categorias(id) ON DELETE SET NULL,
    forma_pagamento TEXT CHECK (forma_pagamento IN ('pix', 'boleto', 'cartao', 'dinheiro', 'transferencia', 'outros')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE financeiro_lancamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to financial records" ON financeiro_lancamentos
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND (
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'financeiro', 'super_admin'))
        OR
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'terapeuta')
    )
);

-- Índices Financeiros
CREATE INDEX IF NOT EXISTS idx_contratos_paciente ON contratos(id_paciente);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_clinica ON financeiro_lancamentos(id_clinica);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_vencimento ON financeiro_lancamentos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_status ON financeiro_lancamentos(status);

-- ============================================================================
-- FIM DO SCHEMA
-- ============================================================================
-- Versão: 1.3.0
-- Última atualização: 07/12/2024
-- Total de tabelas: 21
-- ============================================================================
-- ============================================================================
-- Criação de tabelas para integração com Robô Tirilo
-- ============================================================================

-- 1. Tabela de Frota de Robôs (Autorização)
CREATE TABLE IF NOT EXISTS saas_frota_robos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mac_address TEXT NOT NULL UNIQUE,
    nome_identificacao TEXT,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE SET NULL,
    status_bloqueio BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Configuração de IA por Clínica
CREATE TABLE IF NOT EXISTS clinica_config_ia (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    prompt_personalidade_robo TEXT DEFAULT 'Você é o Tirilo, um robô amigo e terapêutico.',
    motor_voz_preferencial TEXT DEFAULT 'pt-br',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_config_clinica UNIQUE (id_clinica)
);

-- 3. Tabela de Comandos para o Robô (Queue)
CREATE TABLE IF NOT EXISTS comandos_robo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE CASCADE,
    comando TEXT NOT NULL, -- ex: 'FALAR', 'JOGAR_CORES', 'PARAR'
    parametros JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'PENDENTE', -- 'PENDENTE', 'EXECUTADO', 'ERRO'
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    executado_em TIMESTAMPTZ
);

-- 4. Tabela de Telemetria/Logs da Sessão
CREATE TABLE IF NOT EXISTS sessao_telemetria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE SET NULL,
    jogo TEXT, -- qual jogo ou atividade
    resultado TEXT, -- 'venceu', 'perdeu', 'log'
    detalhes JSONB DEFAULT '{}'::jsonb, -- dados extras
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE saas_frota_robos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinica_config_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE comandos_robo ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessao_telemetria ENABLE ROW LEVEL SECURITY;

-- Admin/Super Admin vê tudo
CREATE POLICY "Admin/Super vê todas frotas" ON saas_frota_robos
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil IN ('admin', 'super_admin')));

CREATE POLICY "Admin/Super vê configs" ON clinica_config_ia
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil IN ('admin', 'super_admin')));

CREATE POLICY "Admin/Super gerencia comandos" ON comandos_robo
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil IN ('admin', 'super_admin')));

CREATE POLICY "Admin/Super vê telemetria" ON sessao_telemetria
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil IN ('admin', 'super_admin')));

-- Robô: Acesso via Service Role (Bypassed) ou Policies específicas para chamadas autenticadas como 'anon/robot_role' se implementado.
-- (Atualmente o SaaS usa Service Role para registrar e enviar comandos evitando RLS complexo para o usuário)
-- Para leitura pública do robô (se não usar anon key):
CREATE POLICY "Robo le comandos" ON comandos_robo FOR SELECT USING (true);
CREATE POLICY "Robo atualiza comandos" ON comandos_robo FOR UPDATE USING (true);
CREATE POLICY "Robo insere telemetria" ON sessao_telemetria FOR INSERT WITH CHECK (true);
CREATE POLICY "Robo le config" ON clinica_config_ia FOR SELECT USING (true);
CREATE POLICY "Robo verifica frota" ON saas_frota_robos FOR SELECT USING (true);



-- 2. Tabela de ConfiguraÃ§Ã£o de IA por ClÃ­nica
CREATE TABLE IF NOT EXISTS clinica_config_ia (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_clinica UUID REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    prompt_personalidade_robo TEXT DEFAULT 'VocÃª Ã© o Tirilo, um robÃ´ amigo e terapÃªutico.',
    motor_voz_preferencial TEXT DEFAULT 'pt-br',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_config_clinica UNIQUE (id_clinica)
);

-- 3. Tabela de Comandos para o RobÃ´ (Queue)
CREATE TABLE IF NOT EXISTS comandos_robo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE CASCADE,
    comando TEXT NOT NULL, -- ex: 'FALAR', 'JOGAR_CORES', 'PARAR'
    parametros JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'PENDENTE', -- 'PENDENTE', 'EXECUTADO', 'ERRO'
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    executado_em TIMESTAMPTZ
);

-- 4. Tabela de Telemetria/Logs da SessÃ£o
CREATE TABLE IF NOT EXISTS sessao_telemetria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE SET NULL,
    jogo TEXT, -- qual jogo ou atividade
    resultado TEXT, -- 'venceu', 'perdeu', 'log'
    detalhes JSONB DEFAULT '{}'::jsonb, -- dados extras
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies (Simplificado para MVP/Admin)
ALTER TABLE saas_frota_robos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinica_config_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE comandos_robo ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessao_telemetria ENABLE ROW LEVEL SECURITY;

-- Permitir leitura pÃºblica para robÃ´s (via API Key/Anon se necessÃ¡rio, ou restringir depois)
-- Por enquanto, usaremos service_role ou anon key no robo, polÃ­ticas focadas no admin do saas

-- Admin vÃª tudo
CREATE POLICY "Admin vÃª todas frotas" ON saas_frota_robos
    FOR ALL USING (auth.uid() IN (SELECT user_id FROM equipe WHERE cargo = 'Admin'));

CREATE POLICY "Admin vÃª configs" ON clinica_config_ia
    FOR ALL USING (auth.uid() IN (SELECT user_id FROM equipe WHERE cargo = 'Admin'));

CREATE POLICY "Admin gerencia comandos" ON comandos_robo
    FOR ALL USING (auth.uid() IN (SELECT user_id FROM equipe WHERE cargo = 'Admin'));

CREATE POLICY "Admin vÃª telemetria" ON sessao_telemetria
    FOR ALL USING (auth.uid() IN (SELECT user_id FROM equipe WHERE cargo = 'Admin'));

-- RobÃ´ (Anon/Service) precisa ler/escrever. 
-- Idealmente configurariamos um role postgres 'robot_role', mas para MVP via supabase-py client:
-- Se o robÃ´ usa 'service_role' key, ele ignora RLS.
-- Se usa 'anon' key, precisamos liberar:

CREATE POLICY "Robo le comandos" ON comandos_robo
    FOR SELECT USING (true); -- Refinar para mac_address depois se autenticado

CREATE POLICY "Robo atualiza comandos" ON comandos_robo
    FOR UPDATE USING (true);

CREATE POLICY "Robo insere telemetria" ON sessao_telemetria
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Robo le config" ON clinica_config_ia
    FOR SELECT USING (true);

CREATE POLICY "Robo verifica frota" ON saas_frota_robos
    FOR SELECT USING (true);
-- CriaÃ§Ã£o de tabelas para integraÃ§Ã£o com RobÃ´ Tirilo

-- 1. Tabela de Frota de RobÃ´s (AutorizaÃ§Ã£o)
CREATE TABLE IF NOT EXISTS saas_frota_robos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mac_address TEXT NOT NULL UNIQUE,
    nome_identificacao TEXT,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE SET NULL,
    status_bloqueio BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);
- -   C r e a t e   t a b l e   f o r   G a m e s  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ j o g o s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         n o m e   T E X T   N O T   N U L L ,  
         d e s c r i c a o _ r e g r a s   T E X T ,  
         i n d i c a c a o   T E X T ,  
         t h u m b n a i l _ u r l   T E X T ,  
         a t i v o   B O O L E A N   D E F A U L T   T R U E ,  
         c a t e g o r i a   T E X T ,  
         c o m a n d o _ e n t r a d a   T E X T ,   - -   e . g .   ' g a m e s . p a r e a r _ c o r '   o r   s c r i p t   n a m e  
         c r i a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         a t u a l i z a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( )  
 ) ;  
  
 - -   R L S  
 A L T E R   T A B L E   s a a s _ j o g o s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 - -   P o l i c i e s  
 - -   A d m i n   s e e s   a l l  
 C R E A T E   P O L I C Y   " A d m i n   v e   t o d o s   j o g o s "   O N   s a a s _ j o g o s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;   - -   S i m p l i f i c a n d o   l e i t u r a   g e r a l   p o r   e n q u a n t o ,   o u   r e s t r i n g i r   a   u s u a r i o s   a u t e n t i c a d o s  
  
 C R E A T E   P O L I C Y   " A d m i n   g e r e n c i a   j o g o s "   O N   s a a s _ j o g o s  
         F O R   A L L   U S I N G   ( a u t h . u i d ( )   I N   ( S E L E C T   i d   F R O M   u s u a r i o s   W H E R E   t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' ) ) ) ;  
  
 - -   O p t i o n a l   b u c k e t   f o r   t h u m b n a i l s   i f   n o t   e x i s t s  
 - -   I N S E R T   I N T O   s t o r a g e . b u c k e t s   ( i d ,   n a m e ,   p u b l i c )    
 - -   V A L U E S   ( ' s a a s - j o g o s - a s s e t s ' ,   ' s a a s - j o g o s - a s s e t s ' ,   t r u e )    
 - -   O N   C O N F L I C T   ( i d )   D O   N O T H I N G ;  
  
 - -   P o l i c y   f o r   b u c k e t  
 - -   C R E A T E   P O L I C Y   " P u b l i c   A c c e s s   J o g o s   A s s e t s "   O N   s t o r a g e . o b j e c t s   F O R   S E L E C T   U S I N G   ( b u c k e t _ i d   =   ' s a a s - j o g o s - a s s e t s ' ) ;  
 - -   C R E A T E   P O L I C Y   " A d m i n   U p l o a d   J o g o s   A s s e t s "   O N   s t o r a g e . o b j e c t s   F O R   I N S E R T   W I T H   C H E C K   ( b u c k e t _ i d   =   ' s a a s - j o g o s - a s s e t s '   A N D   a u t h . u i d ( )   I N   ( S E L E C T   i d   F R O M   u s u a r i o s   W H E R E   t i p o _ p e r f i l   =   ' a d m i n ' ) ) ;  
 - -   A d d   v e r s i o n   c o n t r o l   f o r   g a m e s  
  
 - -   1 .   A d d   c u r r e n t   v e r s i o n   t o   m a i n   t a b l e  
 A L T E R   T A B L E   s a a s _ j o g o s    
 A D D   C O L U M N   I F   N O T   E X I S T S   v e r s a o _ a t u a l   T E X T   D E F A U L T   ' 1 . 0 ' ;  
  
 - -   2 .   C r e a t e   v e r s i o n s   h i s t o r y   t a b l e  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ j o g o s _ v e r s o e s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         j o g o _ i d   U U I D   R E F E R E N C E S   s a a s _ j o g o s ( i d )   O N   D E L E T E   C A S C A D E ,  
         v e r s a o   T E X T   N O T   N U L L ,  
         n o t a s _ a t u a l i z a c a o   T E X T ,   - -   C h a n g e l o g   /   D e s c r i p t i o n   o f   c h a n g e s  
         c r i a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         c r i a d o _ p o r   U U I D   R E F E R E N C E S   u s u a r i o s ( i d )   O N   D E L E T E   S E T   N U L L  
 ) ;  
  
 - -   R L S  
 A L T E R   T A B L E   s a a s _ j o g o s _ v e r s o e s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 C R E A T E   P O L I C Y   " A d m i n   v e   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;  
  
 C R E A T E   P O L I C Y   " A d m i n   g e r e n c i a   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   A L L   U S I N G   ( a u t h . u i d ( )   I N   ( S E L E C T   i d   F R O M   u s u a r i o s   W H E R E   t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' ) ) ) ;  
 - -   C O R R E � ! � �O   D E   P E R M I S S � " E S   ( R L S )  
 - -   S i g a   a   o r d e m   d e   e x e c u � � � � o   a b a i x o   p a r a   c o r r i g i r   o   e r r o .  
  
 - -   1 .   L i m p a r   p o l i c i e s   a n t i g a s   p a r a   e v i t a r   c o n f l i t o s  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   v e   t o d o s   j o g o s "   O N   s a a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   g e r e n c i a   j o g o s "   O N   s a a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   v e   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   g e r e n c i a   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s ;  
  
 - -   2 .   R e c r i a r   P o l i c i e s   p a r a   T a b e l a   d e   J o g o s   ( s a a s _ j o g o s )  
 - -   P e r m i t e   l e i t u r a   p a r a   t o d o s   ( p a r a   o   r o b � �   e   u s u � � r i o s   v e r e m )  
 C R E A T E   P O L I C Y   " J o g o s   -   L e i t u r a   G e r a l "   O N   s a a s _ j o g o s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;  
  
 - -   P e r m i t e   g e s t � � o   t o t a l   a p e n a s   p a r a   a d m i n s   v e r i f i c a d o   n a   t a b e l a   d e   u s u a r i o s  
 C R E A T E   P O L I C Y   " J o g o s   -   G e s t a o   A d m i n "   O N   s a a s _ j o g o s  
         F O R   A L L    
         T O   a u t h e n t i c a t e d  
         U S I N G   (  
                 E X I S T S   (  
                         S E L E C T   1   F R O M   u s u a r i o s    
                         W H E R E   u s u a r i o s . i d   =   a u t h . u i d ( )    
                         A N D   u s u a r i o s . t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' )  
                 )  
         ) ;  
  
 - -   3 .   R e c r i a r   P o l i c i e s   p a r a   H i s t � � r i c o   ( s a a s _ j o g o s _ v e r s o e s )  
 C R E A T E   P O L I C Y   " V e r s o e s   -   L e i t u r a   G e r a l "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;  
  
 C R E A T E   P O L I C Y   " V e r s o e s   -   G e s t a o   A d m i n "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   A L L    
         T O   a u t h e n t i c a t e d  
         U S I N G   (  
                 E X I S T S   (  
                         S E L E C T   1   F R O M   u s u a r i o s    
                         W H E R E   u s u a r i o s . i d   =   a u t h . u i d ( )    
                         A N D   u s u a r i o s . t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' )  
                 )  
         ) ;  
  
 - -   4 .   P e r m i s s � � e s   d e   S t o r a g e   ( B u c k e t   ' f o t o s ' )  
 - -   T e n t a   c r i a r   p o l i c y   d e   u p l o a d   p a r a   a u t e n t i c a d o s   s e   n � � o   e x i s t i r  
 - -   N o t a :   O   P o s t g r e s   n � � o   t e m   " C R E A T E   P O L I C Y   I F   N O T   E X I S T S " ,   e n t � � o   s e   d e r   e r r o   a q u i ,  
 - -   p r o v a v e l m e n t e   v o c � �   j � �   t e m   p e r m i s s � � o .   I g n o r e   e r r o s   n e s t a   e t a p a   s e   f o r e m   d e   " p o l i c y   a l r e a d y   e x i s t s " .  
  
 B E G I N ;  
     - -   U p l o a d  
     C R E A T E   P O L I C Y   " F o t o s   -   U p l o a d   A u t h "   O N   s t o r a g e . o b j e c t s   F O R   I N S E R T   T O   a u t h e n t i c a t e d   W I T H   C H E C K   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
     - -   U p d a t e  
     C R E A T E   P O L I C Y   " F o t o s   -   U p d a t e   A u t h "   O N   s t o r a g e . o b j e c t s   F O R   U P D A T E   T O   a u t h e n t i c a t e d   U S I N G   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
 E X C E P T I O N   W H E N   O T H E R S   T H E N  
     - -   I g n o r a r   e r r o   s e   p o l i c y   j � �   e x i s t e  
     R A I S E   N O T I C E   ' P o l i c i e s   d e   s t o r a g e   j a   e x i s t e m   o u   d e r a m   c o n f l i t o ,   i g n o r a n d o . . . ' ;  
 E N D ;  
  
 - -   S e l e c t   P u b l i c o   j � �   d e v e   e x i s t i r ,   m a s   r e f o r � � a n d o  
 C R E A T E   P O L I C Y   " F o t o s   -   S e l e c t   P u b l i c o "   O N   s t o r a g e . o b j e c t s   F O R   S E L E C T   U S I N G   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
 - -   E M E R G E N C Y   F I X   F O R   G A M E S   R L S  
 - -   T e m p o r a r i l y   s i m p l i f y i n g   p e r m i s s i o n s   t o   u n b l o c k   t h e   u s e r .  
 - -   W e   w i l l   r e l y   o n   a p p l i c a t i o n - l e v e l   c h e c k s   f o r   n o w .  
  
 - -   1 .   D r o p   c o n f l i c t i n g   p o l i c i e s  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   v e   t o d o s   j o g o s "   O N   s a a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   g e r e n c i a   j o g o s "   O N   s a a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " J o g o s   -   L e i t u r a   G e r a l "   O N   s a a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " J o g o s   -   G e s t a o   A d m i n "   O N   s a a s _ j o g o s ;  
  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   v e   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n   g e r e n c i a   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " V e r s o e s   -   L e i t u r a   G e r a l "   O N   s a a s _ j o g o s _ v e r s o e s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " V e r s o e s   -   G e s t a o   A d m i n "   O N   s a a s _ j o g o s _ v e r s o e s ;  
  
 - -   2 .   C r e a t e   P e r m i s s i v e   P o l i c i e s   ( A u t h e n t i c a t e d   O n l y )  
 - -   A l l o w s   a n y   l o g g e d - i n   u s e r   t o   m a n a g e   g a m e s .    
 - -   S i n c e   t h e   / a d m i n   r o u t e   i s   p r o t e c t e d ,   t h i s   i s   a c c e p t a b l e   f o r   u n b l o c k i n g .  
  
 - -   G a m e s   T a b l e  
 C R E A T E   P O L I C Y   " J o g o s   -   A u t h e n t i c a t e d   F u l l   A c c e s s "   O N   s a a s _ j o g o s  
         F O R   A L L    
         T O   a u t h e n t i c a t e d  
         U S I N G   ( t r u e )  
         W I T H   C H E C K   ( t r u e ) ;  
  
 - -   G a m e s   V e r s i o n s   T a b l e  
 C R E A T E   P O L I C Y   " V e r s o e s   -   A u t h e n t i c a t e d   F u l l   A c c e s s "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   A L L  
         T O   a u t h e n t i c a t e d  
         U S I N G   ( t r u e )  
         W I T H   C H E C K   ( t r u e ) ;  
  
 - -   3 .   E n s u r e   S t o r a g e   B u c k e t   A c c e s s   ( I d e m p o t e n t )  
 D O   $ $  
 B E G I N  
         I N S E R T   I N T O   s t o r a g e . b u c k e t s   ( i d ,   n a m e ,   p u b l i c )    
         V A L U E S   ( ' f o t o s ' ,   ' f o t o s ' ,   t r u e )  
         O N   C O N F L I C T   ( i d )   D O   N O T H I N G ;  
          
         - -   D r o p   o l d   s t o r a g e   p o l i c i e s   t o   b e   s a f e  
         D R O P   P O L I C Y   I F   E X I S T S   " F o t o s   -   U p l o a d   A u t h "   O N   s t o r a g e . o b j e c t s ;  
         D R O P   P O L I C Y   I F   E X I S T S   " F o t o s   -   U p d a t e   A u t h "   O N   s t o r a g e . o b j e c t s ;  
         D R O P   P O L I C Y   I F   E X I S T S   " F o t o s   -   S e l e c t   P u b l i c o "   O N   s t o r a g e . o b j e c t s ;  
  
         - -   C r e a t e   f r e s h   o n e s  
         C R E A T E   P O L I C Y   " F o t o s   -   U p l o a d   A u t h "   O N   s t o r a g e . o b j e c t s   F O R   I N S E R T   T O   a u t h e n t i c a t e d   W I T H   C H E C K   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
         C R E A T E   P O L I C Y   " F o t o s   -   U p d a t e   A u t h "   O N   s t o r a g e . o b j e c t s   F O R   U P D A T E   T O   a u t h e n t i c a t e d   U S I N G   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
         C R E A T E   P O L I C Y   " F o t o s   -   S e l e c t   P u b l i c o "   O N   s t o r a g e . o b j e c t s   F O R   S E L E C T   U S I N G   ( b u c k e t _ i d   =   ' f o t o s ' ) ;  
 E X C E P T I O N   W H E N   O T H E R S   T H E N  
         N U L L ;  
 E N D   $ $ ;  
 - -   A d d   p r i c e   t o   g a m e s  
 A L T E R   T A B L E   s a a s _ j o g o s   A D D   C O L U M N   p r e c o   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ;  
  
 - -   C r e a t e   l i n k   t a b l e   f o r   c l i n i c   a c c e s s  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ c l i n i c a s _ j o g o s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         c l i n i c a _ i d   U U I D   N O T   N U L L   R E F E R E N C E S   s a a s _ c l i n i c a s ( i d )   O N   D E L E T E   C A S C A D E ,  
         j o g o _ i d   U U I D   N O T   N U L L   R E F E R E N C E S   s a a s _ j o g o s ( i d )   O N   D E L E T E   C A S C A D E ,  
         d a t a _ a q u i s i c a o   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         a t i v o   B O O L E A N   D E F A U L T   t r u e ,  
         U N I Q U E ( c l i n i c a _ i d ,   j o g o _ i d )  
 ) ;  
  
 - -   R L S   f o r   l i n k   t a b l e  
 A L T E R   T A B L E   s a a s _ c l i n i c a s _ j o g o s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 - -   A d m i n s   c a n   m a n a g e   e v e r y t h i n g  
 C R E A T E   P O L I C Y   " A d m i n s   m a n a g e   c l i n i c   g a m e s "   O N   s a a s _ c l i n i c a s _ j o g o s  
         F O R   A L L  
         T O   a u t h e n t i c a t e d  
         U S I N G   (  
                 E X I S T S   (  
                         S E L E C T   1   F R O M   u s u a r i o s    
                         W H E R E   u s u a r i o s . i d   =   a u t h . u i d ( )    
                         A N D   u s u a r i o s . t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' )  
                 )  
         ) ;  
  
 - -   C l i n i c s   c a n   v i e w   t h e i r   o w n   g a m e s  
 C R E A T E   P O L I C Y   " C l i n i c s   v i e w   o w n   g a m e s "   O N   s a a s _ c l i n i c a s _ j o g o s  
         F O R   S E L E C T  
         T O   a u t h e n t i c a t e d  
         U S I N G   (  
                 c l i n i c a _ i d   I N   (  
                         S E L E C T   c l i n i c a _ i d   F R O M   u s u a r i o s   W H E R E   i d   =   a u t h . u i d ( )  
                 )  
         ) ;  
 - -   A d d   m o n e t i z a t i o n   a n d   d e t a i l   f i e l d s   t o   f l e e t   t a b l e  
 A L T E R   T A B L E   s a a s _ f r o t a _ r o b o s    
         A D D   C O L U M N   I F   N O T   E X I S T S   m o d e l o _ h a r d w a r e   T E X T ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   v e r s a o _ h a r d w a r e   T E X T ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   n u m e r o _ s e r i e   T E X T ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   f o t o _ u r l   T E X T ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   v a l o r _ v e n d a   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   v a l o r _ a l u g u e l   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ,  
         A D D   C O L U M N   I F   N O T   E X I S T S   s t a t u s _ o p e r a c i o n a l   T E X T   D E F A U L T   ' d i s p o n i v e l ' ;   - -   d i s p o n i v e l ,   m a n u t e n c a o ,   e m _ u s o  
  
 - -   A l l o w   n u l l a b l e   m a c _ a d d r e s s   f o r   p r e - r e g i s t r a t i o n   i f   n e e d e d ,   b u t   s a f e r   t o   k e e p   i t   m a n d a t o r y   f o r   n o w .    
 - -   A s s u m i n g   r e g i s t r a t i o n   i m p l i e s   h a v i n g   t h e   h a r d w a r e   i n f o .  
  
 - -   U p d a t e   R L S   i f   n e e d e d ?  
 - -   E x i s t i n g   p o l i c i e s   c o v e r   ' s a a s _ f r o t a _ r o b o s '   f o r   a d m i n s .   T h a t   s h o u l d   b e   e n o u g h   f o r   m a n a g e m e n t .  
  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
 - -   A T U A L I Z A � ! � �O :   M O N E T I Z A � ! � �O   D E   J O G O S   E   C O N T R O L E   D E   A C E S S O   ( 2 0 2 5 - 1 2 - 0 9 )  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
  
 - -   A d i c i o n a   c o l u n a   d e   p r e � � o   n a   t a b e l a   d e   j o g o s  
 A L T E R   T A B L E   s a a s _ j o g o s   A D D   C O L U M N   I F   N O T   E X I S T S   p r e c o   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ;  
  
 - -   C r i a   t a b e l a   d e   v � � n c u l o   p a r a   c o n t r o l e   d e   a c e s s o   d a s   c l � � n i c a s   a o s   j o g o s  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ c l i n i c a s _ j o g o s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         c l i n i c a _ i d   B I G I N T   N O T   N U L L   R E F E R E N C E S   s a a s _ c l i n i c a s ( i d )   O N   D E L E T E   C A S C A D E ,  
         j o g o _ i d   U U I D   N O T   N U L L   R E F E R E N C E S   s a a s _ j o g o s ( i d )   O N   D E L E T E   C A S C A D E ,  
         d a t a _ a q u i s i c a o   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         a t i v o   B O O L E A N   D E F A U L T   t r u e ,  
         U N I Q U E ( c l i n i c a _ i d ,   j o g o _ i d )  
 ) ;  
  
 - -   H a b i l i t a   R L S   ( S e g u r a n � � a )   p a r a   a   n o v a   t a b e l a  
 A L T E R   T A B L E   s a a s _ c l i n i c a s _ j o g o s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 - -   P o l � � t i c a   S i m p l i f i c a d a   ( A u t e n t i c a d o s   g e r e n c i a m ,   c o n t r o l e   f i n o   v i a   A p p   A d m i n )  
 D R O P   P O L I C Y   I F   E X I S T S   " A d m i n s   m a n a g e   c l i n i c   g a m e s "   O N   s a a s _ c l i n i c a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " C l i n i c s   v i e w   o w n   g a m e s "   O N   s a a s _ c l i n i c a s _ j o g o s ;  
 D R O P   P O L I C Y   I F   E X I S T S   " A u t h e n t i c a t e d   u s e r s   m a n a g e   m o n e t i z a t i o n "   O N   s a a s _ c l i n i c a s _ j o g o s ;  
  
 C R E A T E   P O L I C Y   " A u t h e n t i c a t e d   u s e r s   m a n a g e   m o n e t i z a t i o n "   O N   s a a s _ c l i n i c a s _ j o g o s  
         F O R   A L L  
         T O   a u t h e n t i c a t e d  
         U S I N G   ( t r u e )  
         W I T H   C H E C K   ( t r u e ) ;  
  
 - -   ( N o t a :   A   t a b e l a   d e   F r o t a s   ( s a a s _ f r o t a _ r o b o s )   j � �   f o i   a t u a l i z a d a   c o m   c a m p o s   d e   H W   e   V a l o r e s   e m   a t u a l i z a � � � � o   a n t e r i o r   n e s t e   a r q u i v o )  
 - -   C r e a t e   t a b l e   f o r   m a i n t e n a n c e   o r d e r s   ( S e r v i c e   O r d e r s   -   O S )  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ m a n u t e n c o e s _ f r o t a   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         r o b o _ i d   U U I D   N O T   N U L L   R E F E R E N C E S   s a a s _ f r o t a _ r o b o s ( i d )   O N   D E L E T E   C A S C A D E ,  
         d a t a _ e n t r a d a   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         d a t a _ f e c h a m e n t o   T I M E S T A M P T Z ,  
          
         t i p o _ m a n u t e n c a o   T E X T   N O T   N U L L   C H E C K   ( t i p o _ m a n u t e n c a o   I N   ( ' p r e v e n t i v a ' ,   ' c o r r e t i v a ' ,   ' u p g r a d e ' ,   ' p r e p a r a c a o ' ,   ' o u t r o s ' ) ) ,  
         s t a t u s _ o s   T E X T   N O T   N U L L   D E F A U L T   ' a b e r t o '   C H E C K   ( s t a t u s _ o s   I N   ( ' a b e r t o ' ,   ' e m _ a n a l i s e ' ,   ' a g u a r d a n d o _ p e c a ' ,   ' e m _ r e p a r o ' ,   ' t e s t e s ' ,   ' c o n c l u i d o ' ,   ' c a n c e l a d o ' ) ) ,  
          
         d e f e i t o _ r e l a t a d o   T E X T ,  
         d i a g n o s t i c o _ t e c n i c o   T E X T ,  
         s o l u c a o _ a p l i c a d a   T E X T ,  
          
         c u s t o _ t o t a l   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ,  
         f a t u r a d o _ c l i e n t e   B O O L E A N   D E F A U L T   f a l s e ,  
          
         c r i a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         a t u a l i z a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( )  
 ) ;  
  
 - -   R L S  
 A L T E R   T A B L E   s a a s _ m a n u t e n c o e s _ f r o t a   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 - -   A d m i n s   m a n a g e   e v e r y t h i n g  
 C R E A T E   P O L I C Y   " A d m i n s   m a n a g e   m a i n t e n a n c e "   O N   s a a s _ m a n u t e n c o e s _ f r o t a  
         F O R   A L L  
         T O   a u t h e n t i c a t e d  
         U S I N G   (  
                 E X I S T S   (  
                         S E L E C T   1   F R O M   u s u a r i o s    
                         W H E R E   u s u a r i o s . i d   =   a u t h . u i d ( )    
                         A N D   u s u a r i o s . t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' )  
                 )  
         ) ;  
  
 - -   C r e a t e   i n d e x   f o r   f a s t e r   l o o k u p s  
 C R E A T E   I N D E X   i d x _ m a n u t e n c a o _ r o b o   O N   s a a s _ m a n u t e n c o e s _ f r o t a ( r o b o _ i d ) ;  
 C R E A T E   I N D E X   i d x _ m a n u t e n c a o _ s t a t u s   O N   s a a s _ m a n u t e n c o e s _ f r o t a ( s t a t u s _ o s ) ;  
  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
 - -   M �  D U L O   D E   J O G O S   E   V E R S � " E S   ( A D I C I O N A D O   E M   2 0 2 5 - 1 2 - 1 0 )  
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
  
 - -   T a b e l a   P r i n c i p a l   d e   J o g o s  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ j o g o s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         n o m e   T E X T   N O T   N U L L ,  
         d e s c r i c a o _ r e g r a s   T E X T ,  
         i n d i c a c a o   T E X T ,  
         t h u m b n a i l _ u r l   T E X T ,  
         a t i v o   B O O L E A N   D E F A U L T   T R U E ,  
         c a t e g o r i a   T E X T ,  
         c o m a n d o _ e n t r a d a   T E X T ,   - -   e . g .   ' g a m e s . p a r e a r _ c o r '   o r   s c r i p t   n a m e  
         p r e c o   D E C I M A L ( 1 0 , 2 )   D E F A U L T   0 . 0 0 ,   - -   A d i c i o n a d o   v i a   m i g r a t e   m o n e t i z e  
         v e r s a o _ a t u a l   T E X T   D E F A U L T   ' 1 . 0 ' ,     - -   A d i c i o n a d o   v i a   m i g r a t e   v e r s i o n s  
         c r i a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         a t u a l i z a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( )  
 ) ;  
  
 - -   R L S :   J o g o s  
 A L T E R   T A B L E   s a a s _ j o g o s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 C R E A T E   P O L I C Y   " A d m i n   v e   t o d o s   j o g o s "   O N   s a a s _ j o g o s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;  
  
 C R E A T E   P O L I C Y   " A d m i n   g e r e n c i a   j o g o s "   O N   s a a s _ j o g o s  
         F O R   A L L   U S I N G   ( a u t h . u i d ( )   I N   ( S E L E C T   i d   F R O M   u s u a r i o s   W H E R E   t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' ) ) ) ;  
  
 - -   T a b e l a   d e   V e r s � � e s   d e   J o g o s  
 C R E A T E   T A B L E   I F   N O T   E X I S T S   s a a s _ j o g o s _ v e r s o e s   (  
         i d   U U I D   P R I M A R Y   K E Y   D E F A U L T   g e n _ r a n d o m _ u u i d ( ) ,  
         j o g o _ i d   U U I D   R E F E R E N C E S   s a a s _ j o g o s ( i d )   O N   D E L E T E   C A S C A D E ,  
         v e r s a o   T E X T   N O T   N U L L ,  
         n o t a s _ a t u a l i z a c a o   T E X T ,    
         c r i a d o _ e m   T I M E S T A M P T Z   D E F A U L T   N O W ( ) ,  
         c r i a d o _ p o r   U U I D   R E F E R E N C E S   u s u a r i o s ( i d )   O N   D E L E T E   S E T   N U L L  
 ) ;  
  
 - -   R L S :   V e r s � � e s  
 A L T E R   T A B L E   s a a s _ j o g o s _ v e r s o e s   E N A B L E   R O W   L E V E L   S E C U R I T Y ;  
  
 C R E A T E   P O L I C Y   " A d m i n   v e   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   S E L E C T   U S I N G   ( t r u e ) ;  
  
 C R E A T E   P O L I C Y   " A d m i n   g e r e n c i a   v e r s o e s "   O N   s a a s _ j o g o s _ v e r s o e s  
         F O R   A L L   U S I N G   ( a u t h . u i d ( )   I N   ( S E L E C T   i d   F R O M   u s u a r i o s   W H E R E   t i p o _ p e r f i l   I N   ( ' a d m i n ' ,   ' s u p e r _ a d m i n ' ) ) ) ;  
 