-- ============================================================================
-- TIRILO SAAS - SCHEMA COMPLETO DO BANCO DE DADOS
-- ============================================================================
-- Descrição: Schema consolidado de todas as tabelas do sistema Tirilo
-- Versão: 1.2.0
-- Data: 04/12/2024
-- 
-- IMPORTANTE: Este arquivo representa o estado FINAL do banco de dados.
-- Use este arquivo para:
--   1. Documentação do schema
--   2. Criar banco de dados em novo servidor
--   3. Referência para desenvolvimento
-- 
-- Ordem de execução:
--   1. Tabelas principais (sem dependências)
--   2. Tabelas com foreign keys
--   3. Políticas RLS
--   4. Storage buckets e políticas
-- ============================================================================

-- ============================================================================
-- 1. TABELAS PRINCIPAIS (SEM DEPENDÊNCIAS)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: saas_clinicas
-- Descrição: Armazena informações das clínicas cadastradas no SaaS
-- Acesso: Apenas Super Admin (master)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saas_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia TEXT NOT NULL,                    -- Nome comercial da clínica
    razao_social TEXT NOT NULL,                     -- Razão social (CNPJ)
    cnpj TEXT,                                       -- CNPJ da clínica
    telefone TEXT,                                   -- Telefone principal
    email TEXT,                                      -- Email de contato
    endereco TEXT,                                   -- Endereço completo
    cidade TEXT,                                     -- Cidade
    estado TEXT,                                     -- Estado (UF)
    cep TEXT,                                        -- CEP
    logo_url TEXT,                                   -- URL do logo no storage
    config_cor_primaria TEXT DEFAULT '#3b82f6',     -- Cor primária da marca
    ativa BOOLEAN DEFAULT TRUE,                      -- Status da clínica
    max_terapeutas INTEGER DEFAULT 5,                -- Limite de terapeutas
    max_pacientes INTEGER DEFAULT 50,                -- Limite de pacientes
    plano TEXT DEFAULT 'basico',                     -- Plano contratado
    data_vencimento TIMESTAMP WITH TIME ZONE,        -- Vencimento do plano
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Apenas Super Admin pode acessar
ALTER TABLE saas_clinicas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super Admin can view all clinics" ON saas_clinicas
FOR SELECT USING (true);

CREATE POLICY "Super Admin can insert clinics" ON saas_clinicas
FOR INSERT WITH CHECK (true);

CREATE POLICY "Super Admin can update clinics" ON saas_clinicas
FOR UPDATE USING (true);

-- ============================================================================
-- 2. TABELAS DE USUÁRIOS E AUTENTICAÇÃO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: usuarios
-- Descrição: Usuários do sistema (Gestores, Terapeutas, Recepcionistas)
-- Nota: Super Admin NÃO tem registro aqui (identificado por ausência de id_clinica)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,                      -- Email de login
    nome_completo TEXT NOT NULL,                     -- Nome completo do usuário
    apelido TEXT,                                    -- Nome curto/apelido (ex: "Dr. João", "Mari")
    tipo_perfil TEXT NOT NULL CHECK (tipo_perfil IN ('admin', 'terapeuta', 'recepcao')),
    celular_whatsapp TEXT,                           -- Telefone/WhatsApp
    foto_url TEXT,                                   -- URL da foto de perfil
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do usuário (soft delete)
    precisa_trocar_senha BOOLEAN DEFAULT TRUE,       -- Flag para primeiro acesso
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS: Usuários veem apenas da sua clínica
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view users from their clinic" ON usuarios
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    OR id = auth.uid()
);

CREATE POLICY "Admins can insert users" ON usuarios
FOR INSERT WITH CHECK (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin')
);

CREATE POLICY "Users can update their own profile" ON usuarios
FOR UPDATE USING (id = auth.uid());

CREATE POLICY "Admins can update users from their clinic" ON usuarios
FOR UPDATE USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin')
);

-- ----------------------------------------------------------------------------
-- TABELA: terapeutas_curriculo
-- Descrição: Currículo e informações profissionais dos terapeutas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS terapeutas_curriculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    registro_profissional TEXT,                      -- CRP, CRM, etc.
    especialidades TEXT[],                           -- Array de especialidades
    formacao_academica TEXT,                         -- Graduação, pós, etc.
    experiencia_anos INTEGER,                        -- Anos de experiência
    bio TEXT,                                        -- Biografia profissional
    curriculo_url TEXT,                              -- URL do currículo em PDF
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE terapeutas_curriculo ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Therapists can view their own curriculum" ON terapeutas_curriculo
FOR SELECT USING (id_usuario = auth.uid());

CREATE POLICY "Therapists can update their own curriculum" ON terapeutas_curriculo
FOR UPDATE USING (id_usuario = auth.uid());

-- ============================================================================
-- 3. TABELAS DE PACIENTES E RESPONSÁVEIS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: responsaveis
-- Descrição: Responsáveis pelos pacientes (pais, tutores)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS responsaveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome_completo TEXT NOT NULL,                     -- Nome do responsável
    cpf TEXT,                                        -- CPF
    email TEXT,                                      -- Email
    telefone TEXT,                                   -- Telefone principal
    celular_whatsapp TEXT,                           -- WhatsApp
    endereco TEXT,                                   -- Endereço completo
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    parentesco TEXT,                                 -- Relação com o paciente
    profissao TEXT,                                  -- Profissão
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE responsaveis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view responsaveis from their clinic" ON responsaveis
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: pacientes
-- Descrição: Pacientes atendidos na clínica
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE SET NULL,
    nome_completo TEXT NOT NULL,                     -- Nome do paciente
    data_nascimento DATE,                            -- Data de nascimento
    cpf TEXT,                                        -- CPF (se aplicável)
    sexo TEXT CHECK (sexo IN ('M', 'F', 'Outro')),  -- Sexo
    foto_url TEXT,                                   -- Foto do paciente
    telefone TEXT,                                   -- Telefone (se tiver)
    email TEXT,                                      -- Email (se tiver)
    endereco TEXT,                                   -- Endereço
    cidade TEXT,
    estado TEXT,
    cep TEXT,
    escola TEXT,                                     -- Escola que frequenta
    serie_ano TEXT,                                  -- Série/Ano escolar
    turno_escolar TEXT,                              -- Manhã, Tarde, Integral
    observacoes TEXT,                                -- Observações gerais
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do paciente
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view pacientes from their clinic" ON pacientes
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: pacientes_terapeutas
-- Descrição: Relacionamento N:N entre pacientes e terapeutas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pacientes_terapeutas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    data_inicio DATE DEFAULT CURRENT_DATE,           -- Início do acompanhamento
    data_fim DATE,                                   -- Fim do acompanhamento
    ativo BOOLEAN DEFAULT TRUE,                      -- Relacionamento ativo
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(id_paciente, id_terapeuta)
);

ALTER TABLE pacientes_terapeutas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their clinic's patient-therapist relationships" ON pacientes_terapeutas
FOR SELECT USING (
    id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid()))
);

-- ----------------------------------------------------------------------------
-- TABELA: anamnese
-- Descrição: Anamnese e histórico clínico dos pacientes
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS anamnese (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL UNIQUE,
    queixa_principal TEXT,                           -- Motivo da consulta
    historico_familiar TEXT,                         -- Histórico familiar
    historico_gestacional TEXT,                      -- Gestação e parto
    desenvolvimento_motor TEXT,                      -- Desenvolvimento motor
    desenvolvimento_linguagem TEXT,                  -- Desenvolvimento da linguagem
    historico_escolar TEXT,                          -- Histórico escolar
    medicamentos_uso TEXT,                           -- Medicamentos em uso
    alergias TEXT,                                   -- Alergias
    diagnosticos_previos TEXT,                       -- Diagnósticos anteriores
    laudo_medico_arquivo_url TEXT,                   -- Path do laudo no storage
    observacoes_clinicas TEXT,                       -- Observações do terapeuta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE anamnese ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view anamnese from their clinic" ON anamnese
FOR SELECT USING (
    id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid()))
);

-- ============================================================================
-- 4. TABELAS DE AGENDAMENTOS E SALAS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: salas
-- Descrição: Salas de atendimento da clínica
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS salas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,                              -- Nome da sala (ex: "Sala 1")
    descricao TEXT,                                  -- Descrição da sala
    capacidade INT DEFAULT 1,                        -- Capacidade de pessoas
    cor_identificacao TEXT DEFAULT '#3b82f6',        -- Cor para identificação visual
    foto_url TEXT,                                   -- URL da foto da sala (Supabase Storage)
    ativa BOOLEAN DEFAULT TRUE,                      -- Status da sala
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE salas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view salas from their clinic" ON salas
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: agendamentos
-- Descrição: Agendamentos de sessões
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE CASCADE NOT NULL,
    id_sala BIGINT REFERENCES salas(id) ON DELETE SET NULL,
    data_hora_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_hora_fim TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'agendado' CHECK (status IN ('agendado', 'em_andamento', 'concluido', 'cancelado')),
    tipo_sessao TEXT,                                -- Tipo de sessão (avaliação, terapia, etc.)
    observacoes TEXT,                                -- Observações do agendamento
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view agendamentos from their clinic" ON agendamentos
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ============================================================================
-- 5. TABELAS DE RELATÓRIOS E EVOLUÇÃO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: relatorios
-- Descrição: Relatórios e evoluções das sessões
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS relatorios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL NOT NULL,
    id_agendamento BIGINT REFERENCES agendamentos(id) ON DELETE SET NULL,
    data_sessao DATE NOT NULL,                       -- Data da sessão
    tipo_relatorio TEXT DEFAULT 'evolucao',          -- Tipo (evolução, avaliação, etc.)
    titulo TEXT,                                     -- Título do relatório
    conteudo TEXT NOT NULL,                          -- Conteúdo do relatório
    objetivos TEXT,                                  -- Objetivos trabalhados
    atividades TEXT,                                 -- Atividades realizadas
    observacoes TEXT,                                -- Observações
    anexos_urls TEXT[],                              -- URLs de anexos
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE relatorios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Therapists can view their own reports" ON relatorios
FOR SELECT USING (
    id_terapeuta = auth.uid()
    OR id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin'))
);

-- ============================================================================
-- 6. TABELAS DE ASSISTENTE IA
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: prompts_ia
-- Descrição: Prompts customizados para o assistente de IA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS prompts_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL,
    nome TEXT NOT NULL,                              -- Nome do prompt
    descricao TEXT,                                  -- Descrição do prompt
    prompt_texto TEXT NOT NULL,                      -- Texto do prompt
    categoria TEXT,                                  -- Categoria (plano, relatório, etc.)
    ativo BOOLEAN DEFAULT TRUE,                      -- Status do prompt
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE prompts_ia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view prompts from their clinic" ON prompts_ia
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ----------------------------------------------------------------------------
-- TABELA: planos_ia
-- Descrição: Planos de intervenção gerados pela IA
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS planos_ia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE SET NULL NOT NULL,
    id_prompt BIGINT REFERENCES prompts_ia(id) ON DELETE SET NULL,
    titulo TEXT NOT NULL,                            -- Título do plano
    conteudo_gerado TEXT NOT NULL,                   -- Plano gerado pela IA
    modelo_ia TEXT DEFAULT 'gemini-2.0-flash-exp',  -- Modelo usado
    prompt_usado TEXT,                               -- Prompt que foi usado
    aprovado BOOLEAN DEFAULT FALSE,                  -- Se foi aprovado pelo terapeuta
    data_aprovacao TIMESTAMP WITH TIME ZONE,         -- Data de aprovação
    observacoes TEXT,                                -- Observações do terapeuta
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE planos_ia ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Therapists can view their own AI plans" ON planos_ia
FOR SELECT USING (
    id_terapeuta = auth.uid()
    OR id_paciente IN (SELECT id FROM pacientes WHERE id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin'))
);

-- ============================================================================
-- 7. TABELAS DE HELP DESK (SUPORTE)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: help_desk_tickets
-- Descrição: Tickets de suporte abertos pelas clínicas
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS help_desk_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    id_usuario_criador UUID NOT NULL,                -- Pode ser NULL se Super Admin
    assunto TEXT NOT NULL,                           -- Assunto do chamado
    tipo TEXT DEFAULT 'duvida' CHECK (tipo IN ('problema', 'sugestao', 'duvida', 'financeiro', 'outro')),
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_andamento', 'aguardando_cliente', 'resolvido', 'fechado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE help_desk_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tickets" ON help_desk_tickets
FOR SELECT USING (
    id_usuario_criador = auth.uid()
    OR id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    OR auth.uid() IN (SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'master_admin')
);

-- ----------------------------------------------------------------------------
-- TABELA: help_desk_mensagens
-- Descrição: Mensagens dos tickets de suporte
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS help_desk_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket BIGINT REFERENCES help_desk_tickets(id) ON DELETE CASCADE NOT NULL,
    id_usuario UUID,                                 -- NULL se for Super Admin
    mensagem TEXT NOT NULL,                          -- Conteúdo da mensagem
    anexo_url TEXT,                                  -- Path do anexo no storage
    anexo_nome TEXT,                                 -- Nome original do arquivo
    anexo_tipo TEXT,                                 -- MIME type do arquivo
    lida BOOLEAN DEFAULT FALSE,                      -- Se foi lida
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE help_desk_mensagens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view messages from their tickets" ON help_desk_mensagens
FOR SELECT USING (
    id_ticket IN (SELECT id FROM help_desk_tickets WHERE id_usuario_criador = auth.uid() OR id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid()))
);

-- ============================================================================
-- 8. TABELAS DE MATERIAIS E RECURSOS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA: materiais
-- Descrição: Materiais e recursos terapêuticos
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS materiais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,                              -- Nome do material
    descricao TEXT,                                  -- Descrição
    categoria TEXT,                                  -- Categoria (jogo, livro, etc.)
    quantidade INTEGER DEFAULT 1,                    -- Quantidade disponível
    localizacao TEXT,                                -- Onde está guardado
    foto_url TEXT,                                   -- Foto do material
    disponivel BOOLEAN DEFAULT TRUE,                 -- Se está disponível
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE materiais ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view materiais from their clinic" ON materiais
FOR SELECT USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- ============================================================================
-- 9. STORAGE BUCKETS E POLÍTICAS
-- ============================================================================

-- Bucket: laudos (privado)
-- Descrição: Laudos médicos dos pacientes
INSERT INTO storage.buckets (id, name, public)
VALUES ('laudos', 'laudos', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Users can upload laudos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'laudos'
    AND auth.uid() IS NOT NULL
);

CREATE POLICY "Users can view laudos from their clinic" ON storage.objects
FOR SELECT USING (
    bucket_id = 'laudos'
    AND auth.uid() IS NOT NULL
);

-- Bucket: help-desk-anexos (privado)
-- Descrição: Anexos dos tickets de suporte
INSERT INTO storage.buckets (id, name, public)
VALUES ('help-desk-anexos', 'help-desk-anexos', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Users can upload help desk attachments" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'help-desk-anexos'
    AND auth.uid() IS NOT NULL
);

CREATE POLICY "Users can view help desk attachments" ON storage.objects
FOR SELECT USING (
    bucket_id = 'help-desk-anexos'
    AND auth.uid() IS NOT NULL
);

-- Bucket: logos (público)
-- Descrição: Logos das clínicas
INSERT INTO storage.buckets (id, name, public)
VALUES ('logos', 'logos', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Anyone can view logos" ON storage.objects
FOR SELECT USING (bucket_id = 'logos');

CREATE POLICY "Admins can upload logos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'logos'
    AND auth.uid() IS NOT NULL
);


-- Bucket: fotos (público)
-- Descrição: Fotos de salas e materiais
INSERT INTO storage.buckets (id, name, public)
VALUES ('fotos', 'fotos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Permitir visualização pública
CREATE POLICY "Anyone can view fotos" ON storage.objects
FOR SELECT USING (bucket_id = 'fotos');

-- Permitir upload para usuários autenticados
CREATE POLICY "Users can upload fotos" ON storage.objects
FOR INSERT WITH CHECK (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- Permitir atualização para usuários autenticados
CREATE POLICY "Users can update fotos" ON storage.objects
FOR UPDATE USING (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- Permitir exclusão para usuários autenticados
CREATE POLICY "Users can delete fotos" ON storage.objects
FOR DELETE USING (
    bucket_id = 'fotos'
    AND auth.role() = 'authenticated'
);

-- ============================================================================
-- 10. ÍNDICES PARA PERFORMANCE
-- ============================================================================

-- Índices para melhorar performance de queries frequentes
CREATE INDEX IF NOT EXISTS idx_usuarios_id_clinica ON usuarios(id_clinica);
CREATE INDEX IF NOT EXISTS idx_usuarios_tipo_perfil ON usuarios(tipo_perfil);
CREATE INDEX IF NOT EXISTS idx_pacientes_id_clinica ON pacientes(id_clinica);
CREATE INDEX IF NOT EXISTS idx_pacientes_id_responsavel ON pacientes(id_responsavel);
CREATE INDEX IF NOT EXISTS idx_agendamentos_id_clinica ON agendamentos(id_clinica);
CREATE INDEX IF NOT EXISTS idx_agendamentos_id_terapeuta ON agendamentos(id_terapeuta);
CREATE INDEX IF NOT EXISTS idx_agendamentos_data_hora_inicio ON agendamentos(data_hora_inicio);
CREATE INDEX IF NOT EXISTS idx_help_desk_tickets_id_clinica ON help_desk_tickets(id_clinica);
CREATE INDEX IF NOT EXISTS idx_help_desk_mensagens_id_ticket ON help_desk_mensagens(id_ticket);

-- ============================================================================
-- FIM DO SCHEMA
-- ============================================================================
-- Versão: 1.2.0
-- Última atualização: 04/12/2024
-- Total de tabelas: 18
-- ============================================================================
