
-- ============================================================================
-- TIRILO SAAS - SCHEMA DE BANCO DE DADOS (V2.0)
-- Atualizado em: 10/12/2025
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. SAAS & CLÍNICAS
-- ----------------------------------------------------------------------------

CREATE TABLE public.saas_empresa (
    id SERIAL PRIMARY KEY,
    razao_social TEXT NOT NULL,
    nome_fantasia TEXT,
    cnpj TEXT,
    inscricao_estadual TEXT,
    inscricao_municipal TEXT,
    
    -- Endereço Estruturado
    end_logradouro TEXT,
    end_numero TEXT,
    end_complemento TEXT,
    end_bairro TEXT,
    end_cidade TEXT,
    end_estado TEXT,
    end_cep TEXT,

    telefone TEXT,
    email_contato TEXT,
    site_url TEXT,
    logo_url TEXT,
    
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.saas_clinicas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_fantasia TEXT NOT NULL,
    razao_social TEXT,
    cnpj TEXT UNIQUE,
    email_contato TEXT,
    telefone TEXT,
    telefone_fixo TEXT,
    endereco JSONB, -- { "rua": "...", "numero": "...", ... } (Legado/Alternativo)
    
    -- Endereço Estruturado (Adicionado em 12/12/2025)
    end_logradouro TEXT,
    end_numero TEXT,
    end_complemento TEXT,
    end_bairro TEXT,
    end_cidade TEXT,
    end_estado TEXT,
    end_cep TEXT,

    logo_url TEXT,
    
    -- Dados Adicionais (Adicionado em 12/12/2025)
    inscricao_estadual TEXT,
    inscricao_municipal TEXT,
    missao TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    ativo BOOLEAN DEFAULT TRUE,
    max_terapeutas INTEGER,
    plano_atual TEXT,
    status_assinatura TEXT,

    -- Configurações e Customizações
    configuracoes JSONB DEFAULT '{}'::jsonb, -- { "cor_primaria": "#...", ... }
    config_cor_primaria TEXT, -- Adicionado para compatibilidade com produção
    endereco_completo TEXT -- Adicionado para compatibilidade com produção
);

CREATE TABLE public.clinicas_salas (
    id SERIAL PRIMARY KEY,
    id_clinica INTEGER REFERENCES public.saas_clinicas(id),
    nome TEXT NOT NULL,
    descricao TEXT,
    ativo BOOLEAN DEFAULT TRUE
);

CREATE TABLE public.saas_operadoras (
    id SERIAL PRIMARY KEY,
    clinica_id INTEGER REFERENCES public.saas_clinicas(id),
    nome_fantasia TEXT NOT NULL,
    razao_social TEXT,
    cnpj TEXT,
    registro_ans TEXT,
    
    -- Endereço e Contato (Adicionado 1.10.0)
    endereco_logradouro TEXT,
    endereco_numero TEXT,
    endereco_complemento TEXT,
    endereco_bairro TEXT,
    endereco_cidade TEXT,
    endereco_estado TEXT,
    endereco_cep TEXT,
    
    telefone TEXT,
    contato_nome TEXT,
    contato_cargo TEXT,
    
    prazo_pagamento_dias INTEGER, -- Adicionado para compatibilidade com produção
    
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 2. USUÁRIOS & PERMISSÕES
-- ----------------------------------------------------------------------------

CREATE TYPE tipo_usuario_enum AS ENUM ('superadmin', 'gestor', 'terapeuta', 'recepcionista');

CREATE TABLE public.usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    nome TEXT,
    nome_completo TEXT,
    apelido TEXT,
    email TEXT UNIQUE NOT NULL,
    cpf TEXT,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    tipo_perfil TEXT,
    
    -- Dados Terapeuta
    registro_profissional TEXT, -- CRP/CRM (Pode estar em outra tabela ou legada)
    especialidade TEXT,
    bio TEXT,
    foto_url TEXT,
    celular_whatsapp TEXT,
    celular TEXT,
    
    aceita_receber_alertas BOOLEAN DEFAULT TRUE,
    onboarding_concluido BOOLEAN DEFAULT FALSE,
    precisa_trocar_senha BOOLEAN DEFAULT FALSE,

    ativo BOOLEAN DEFAULT TRUE,
    id_perfil UUID, -- Referência ao perfil se houver sistema de roles (opcional)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.terapeutas_curriculo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario UUID REFERENCES public.usuarios(id),
    usuario_id UUID, 
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    
    registro_profissional TEXT,
    formacao_academica TEXT,
    formacao TEXT,
    especialidades_tags JSONB,
    especialidades TEXT[],
    habilidades_tecnicas TEXT,
    publico_alvo_preferencial TEXT,
    publico_alvo TEXT[],
    bio TEXT,
    
    tecnicas_preferidas TEXT,
    recursos_preferidos TEXT,
    estilo_conducao TEXT,
    observacoes_clinicas TEXT,
    
    valor_hora_padrao NUMERIC(10,2),
    porcentagem_repasse NUMERIC(5,2),
    chave_pix TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 3. PACIENTES & FAMÍLIA
-- ----------------------------------------------------------------------------

CREATE TABLE public.pacientes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id) NOT NULL,
    nome TEXT NOT NULL,
    data_nascimento DATE,
    foto_url TEXT,
    foto_perfil_url TEXT,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    
    -- Financeiro e Convênio
    valor_sessao_padrao NUMERIC(10,2),
    dia_vencimento_padrao INTEGER,
    convenio_nome TEXT,
    convenio_numero_carteirinha TEXT,
    convenio_validade DATE,
    operadora_id INTEGER REFERENCES public.saas_operadoras(id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.pacientes_anamnese (
    id SERIAL PRIMARY KEY,
    paciente_id INTEGER REFERENCES public.pacientes(id) ON DELETE CASCADE,
    
    -- Dados Clínicos
    diagnostico_principal TEXT,
    historico_medico TEXT,
    medicamentos_atuais TEXT,
    alergias TEXT,
    
    -- Desenvolvimento
    gestacao_intercorrencias TEXT,
    parto_tipo TEXT,
    desenvolvimento_motor TEXT,
    desenvolvimento_linguagem TEXT,
    
    -- Musicoterapia (Específico)
    musicoterapia JSONB DEFAULT '{}'::jsonb,

    laudo_medico_arquivo_url TEXT,
    laudo_medico_data_upload TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.pacientes_terapeutas (
    paciente_id INTEGER REFERENCES public.pacientes(id) ON DELETE CASCADE,
    terapeuta_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (paciente_id, terapeuta_id)
);

CREATE TABLE public.responsaveis (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    email TEXT,
    user_id UUID
);

CREATE TABLE public.pacientes_responsaveis (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    paciente_id BIGINT REFERENCES public.pacientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES public.responsaveis(id) ON DELETE CASCADE,
    grau_parentesco TEXT,
    responsavel_principal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 4. AGENDAMENTO & FINANCEIRO
-- ----------------------------------------------------------------------------

CREATE TYPE status_agendamento_enum AS ENUM ('AGENDADO', 'CONFIRMADO', 'REALIZADO', 'CONCLUIDO', 'CANCELADO', 'FALTA');

CREATE TABLE public.agendamentos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    id_paciente BIGINT REFERENCES public.pacientes(id),
    id_terapeuta UUID REFERENCES public.usuarios(id),
    id_sala BIGINT REFERENCES public.clinicas_salas(id),
    data_hora_inicio TIMESTAMPTZ NOT NULL,
    data_hora_fim TIMESTAMPTZ NOT NULL,
    tipo_sessao TEXT DEFAULT 'individual',
    status TEXT DEFAULT 'agendado',
    observacoes TEXT,
    id_lancamento_financeiro BIGINT,
    valor_sessao NUMERIC
);

CREATE TABLE public.financeiro_categorias (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL,
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.financeiro_lancamentos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    descricao TEXT NOT NULL,
    valor NUMERIC NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    status TEXT DEFAULT 'pendente',
    tipo TEXT NOT NULL,
    id_paciente BIGINT REFERENCES public.pacientes(id),
    id_responsavel BIGINT REFERENCES public.responsaveis(id),
    id_categoria BIGINT REFERENCES public.financeiro_categorias(id),
    forma_pagamento TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    comprovante_url TEXT
);

-- ----------------------------------------------------------------------------
-- 5. ROBÔS & LUDOTERAPIA (MÓDULO NOVO)
-- ----------------------------------------------------------------------------

-- Catálogo de Habilidades (Loja)
CREATE TABLE public.saas_habilidades (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE, -- Ex: "Foco", "Memória", "Interação Social"
    descricao TEXT,
    codigo_ia TEXT -- Prompt base ou tag para IA
);

-- Catálogo de Jogos (Global)
CREATE TABLE public.saas_jogos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao_regras TEXT,
    indicacao TEXT,
    thumbnail_url TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    categoria TEXT, -- "EDUCATIVO", "MOTOR", "SOCIAL"
    comando_entrada TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    versao_atual TEXT,
    preco NUMERIC(10,2) DEFAULT 0.00,
    demo_video_url TEXT,
    recursos_terapeuticos TEXT
);

-- Relacionamento Jogo <-> Habilidades (N:N)
CREATE TABLE public.saas_jogos_habilidades (
    jogo_id UUID REFERENCES public.saas_jogos(id) ON DELETE CASCADE,
    habilidade_id UUID REFERENCES public.saas_habilidades(id) ON DELETE CASCADE,
    nivel_impacto INTEGER DEFAULT 1, -- 1 a 5
    PRIMARY KEY (jogo_id, habilidade_id)
);

-- Controle de Versões (OTA)
CREATE TABLE public.saas_jogos_versoes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    jogo_id UUID REFERENCES public.saas_jogos(id) ON DELETE CASCADE,
    versao TEXT NOT NULL,
    notas_atualizacao TEXT, -- Antigo 'changelog'
    criado_em TIMESTAMPTZ DEFAULT NOW(), -- Antigo 'created_at'
    criado_por UUID REFERENCES public.usuarios(id)
);

-- Aquisições da Clínica
CREATE TABLE public.saas_clinicas_jogos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    clinica_id BIGINT REFERENCES public.saas_clinicas(id) ON DELETE CASCADE,
    jogo_id UUID REFERENCES public.saas_jogos(id) ON DELETE CASCADE,
    
    ativo BOOLEAN DEFAULT TRUE, -- Se a clínica ativou/desativou
    data_aquisicao TIMESTAMPTZ DEFAULT NOW(),
    validade_ate TIMESTAMPTZ, -- Null = perpétuo
    licenca_tipo TEXT DEFAULT 'PERPETUA', -- PERPETUA, MENSAL, TESTE
    
    UNIQUE(clinica_id, jogo_id)
);

-- Frota de Robôs
CREATE TABLE public.saas_frota_robos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    mac_address TEXT NOT NULL,
    nome_identificacao TEXT,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    status_bloqueio BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    modelo_hardware TEXT,
    versao_hardware TEXT,
    numero_serie TEXT,
    foto_url TEXT,
    valor_venda NUMERIC(10,2) DEFAULT 0.00,
    valor_aluguel NUMERIC(10,2) DEFAULT 0.00,
    status_operacional TEXT DEFAULT 'disponivel',
    endereco_tailscale TEXT,
    usuario_ssh TEXT DEFAULT 'pi',
    modelo_contrato TEXT DEFAULT 'VENDA',
    status_financeiro TEXT DEFAULT 'ADIMPLENTE'
);

-- Configuração de IA da Clínica (Personalidade)
CREATE TABLE public.clinica_config_ia (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id) UNIQUE,
    tom_de_voz TEXT DEFAULT 'Empático e Lúdico',
    restricoes TEXT, -- O que NÃO fazer
    model_version TEXT DEFAULT 'gemini-2.5-flash'
);

-- ----------------------------------------------------------------------------
-- 6. SESSÕES LÚDICAS (HISTÓRICO)
-- ----------------------------------------------------------------------------

CREATE TABLE public.sessao_ludica (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    clinica_id BIGINT REFERENCES public.saas_clinicas(id),
    terapeuta_id UUID REFERENCES public.usuarios(id),
    paciente_id BIGINT REFERENCES public.pacientes(id),
    robo_mac_address TEXT,
    jogo_id UUID REFERENCES public.saas_jogos(id),
    versao_jogo TEXT,
    
    data_inicio TIMESTAMPTZ DEFAULT NOW(),
    data_fim TIMESTAMPTZ,
    duracao_segundos INTEGER,
    
    pontuacao_final INTEGER,
    nivel_dificuldade TEXT, -- FACIL, MEDIO, DIFICIL
    
    -- Métricas estruturadas
    metricas JSONB DEFAULT '{}'::jsonb, -- { "tempolatencia": 2.5, "acertos": 10 }
    
    observacoes_terapeuta TEXT,
    status TEXT DEFAULT 'EM_ANDAMENTO' -- EM_ANDAMENTO, CONCLUIDO, INTERROMPIDO
);

CREATE TABLE public.sessao_diario_bordo (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    sessao_ludica_id UUID REFERENCES public.sessao_ludica(id) ON DELETE CASCADE,
    tipo_evento TEXT, -- FALA_ROBO, FALA_PACIENTE, ACAO_JOGO, INTERVENCAO_TERAPEUTA
    texto_transcrito TEXT, -- O que foi falado (STT/TTS)
    metadados JSONB, -- Emoção detectada, contexto, etc.
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    criado_em TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.sessao_telemetria (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mac_address TEXT,
    jogo TEXT,
    resultado TEXT,
    detalhes JSONB,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Comandos Remotos (Fila)
CREATE TABLE public.comandos_robo (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mac_address TEXT,
    comando TEXT NOT NULL, -- Ex: "update_software", "restart"
    parametros JSONB,
    status TEXT DEFAULT 'PENDENTE',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    executado_em TIMESTAMPTZ
);

-- ----------------------------------------------------------------------------
-- 7. IA GENERATIVA & RELATÓRIOS (V1.7.5)
-- ----------------------------------------------------------------------------

CREATE TABLE public.prompts_ia (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    terapeuta_id UUID REFERENCES public.usuarios(id),
    nome_prompt TEXT NOT NULL,
    descricao TEXT,
    prompt_texto TEXT NOT NULL,
    modelo_gemini TEXT DEFAULT 'gemini-2.5-flash',
    temperatura NUMERIC DEFAULT 0.7,
    ativo BOOLEAN DEFAULT TRUE,
    categoria TEXT DEFAULT 'plano',
    criado_por UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.planos_intervencao_ia (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_paciente BIGINT REFERENCES public.pacientes(id),
    id_terapeuta UUID REFERENCES public.usuarios(id),
    id_prompt_ia BIGINT REFERENCES public.prompts_ia(id), -- Pode ser NULL
    
    titulo TEXT, -- Título do plano (Adicionado V1.7.5)
    plano_final TEXT, -- Texto gerado/importado
    plano_original TEXT, -- Texto raw da IA
    recursos_sugeridos JSONB DEFAULT '[]'::jsonb, -- Lista de materiais/recursos (Adicionado V1.7.5)
    modelo_ia TEXT, -- Versão do modelo usado
    historico_chat JSONB DEFAULT '[]'::jsonb, -- Histórico de conversa para refinamento
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.relatorios_atendimento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_agendamento BIGINT REFERENCES public.agendamentos(id),
    id_paciente BIGINT REFERENCES public.pacientes(id),
    id_terapeuta UUID REFERENCES public.usuarios(id),
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    id_prompt_ia BIGINT REFERENCES public.prompts_ia(id),

    texto_bruto TEXT, -- Notas originais do terapeuta
    relatorio_gerado TEXT, -- Texto final melhorado pela IA
    status TEXT DEFAULT 'rascunho', -- 'rascunho', 'finalizado'
    visivel_familia BOOLEAN DEFAULT FALSE, -- Controle de visibilidade para o Portal da Família

    
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------------------
-- 8. OUTRAS TABELAS (SUPLEMENTARES)
-- ----------------------------------------------------------------------------

CREATE TABLE public.saas_manutencoes_frota (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    robo_id UUID REFERENCES public.saas_frota_robos(id),
    data_entrada TIMESTAMPTZ,
    data_fechamento TIMESTAMPTZ,
    tipo_manutencao TEXT, -- PREVENTIVA, CORRETIVA
    status_os TEXT, -- PENDENTE, EM_ANDAMENTO, CONCLUIDO
    defeito_relatado TEXT,
    diagnostico_tecnico TEXT,
    solucao_aplicada TEXT,
    custo_total NUMERIC(10,2),
    faturado_cliente BOOLEAN DEFAULT FALSE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE public.contratos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    id_paciente BIGINT REFERENCES public.pacientes(id),
    id_responsavel BIGINT REFERENCES public.responsaveis(id),
    tipo_cobranca TEXT NOT NULL,
    valor NUMERIC NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    dia_vencimento INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'ativo',
    arquivo_url TEXT,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    id_terapeuta UUID
);

-- Cadastro de Salas (Usado em agenda e salas.ts)
CREATE TABLE public.salas_recursos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    nome TEXT NOT NULL,
    descricao TEXT,
    capacidade INTEGER,
    cor_identificacao TEXT,
    cor_hex TEXT, -- Usado na agenda
    foto_url TEXT,
    icone TEXT,
    observacoes TEXT,
    ativo BOOLEAN DEFAULT TRUE,
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cadastro de Materiais/Recursos
CREATE TABLE public.recursos (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    nome_item TEXT NOT NULL,
    foto_url TEXT,
    localizacao TEXT,
    quantidade INTEGER DEFAULT 1,
    objetivos_terapeuticos TEXT[],
    status_conservacao TEXT DEFAULT 'Excelente',
    descricao TEXT
);

CREATE TABLE public.help_desk_tickets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_clinica BIGINT REFERENCES public.saas_clinicas(id),
    id_usuario_criador UUID, 
    assunto TEXT NOT NULL,
    tipo TEXT NOT NULL,
    prioridade TEXT DEFAULT 'media',
    status TEXT DEFAULT 'aberto',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.help_desk_mensagens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_ticket BIGINT REFERENCES public.help_desk_tickets(id),
    id_usuario UUID,
    mensagem TEXT NOT NULL,
    anexo_url TEXT,
    lida BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    anexo_nome TEXT,
    anexo_tipo TEXT
);
-- ----------------------------------------------------------------------------
-- 9. PERMISSÕES BÁSICAS (RESTAURAÇÃO PÓS-CLEANUP)
-- ----------------------------------------------------------------------------

-- Garantir que as roles padrão do Supabase tenham acesso ao schema public
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- Garantir acesso a todas as tabelas, sequências e funções
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;

-- Configurar o schema public como padrão para as roles (opcional, mas recomendado)
ALTER ROLE anon SET search_path TO public;
ALTER ROLE authenticated SET search_path TO public;
ALTER ROLE service_role SET search_path TO public;

-- ----------------------------------------------------------------------------
-- POLÍTICAS DE SEGURANÇA (RLS) - PROMPTS IA
-- ----------------------------------------------------------------------------

ALTER TABLE public.prompts_ia ENABLE ROW LEVEL SECURITY;

-- Política de Leitura (SELECT):
-- Permite que qualquer usuário da mesma clínica leia os prompts.
-- Isso inclui terapeutas vendo prompts de admins (para clonagem).
DROP POLICY IF EXISTS "Prompts Policy Select" ON prompts_ia;
CREATE POLICY "Prompts Policy Select" ON prompts_ia
FOR SELECT
USING (
  id_clinica IN (
    SELECT id_clinica FROM usuarios WHERE id = auth.uid()
  )
);

-- Política de Inserção (INSERT):
-- Usuários podem criar prompts para sua clínica.
-- Se for Admin/Super, pode criar em nome de outros (mas a aplicação decide).
DROP POLICY IF EXISTS "Prompts Policy Insert" ON prompts_ia;
CREATE POLICY "Prompts Policy Insert" ON prompts_ia
FOR INSERT
WITH CHECK (
  id_clinica IN (
    SELECT id_clinica FROM usuarios WHERE id = auth.uid()
  )
);

-- Política de Atualização (UPDATE):
-- Permite editar apenas os PRÓPRIOS prompts ou se for Admin não-terapeuta.
DROP POLICY IF EXISTS "Prompts Policy Update" ON prompts_ia;
CREATE POLICY "Prompts Policy Update" ON prompts_ia
FOR UPDATE
USING (
  id_clinica IN (
    SELECT id_clinica FROM usuarios WHERE id = auth.uid()
  )
  AND (
    terapeuta_id = auth.uid()
    OR
    EXISTS (
      SELECT 1 FROM usuarios 
      WHERE id = auth.uid() 
      AND tipo_perfil != 'terapeuta'
    )
  )
);

-- Política de Exclusão (DELETE):
-- Mesma regra de atualização: Dono ou Admin.
DROP POLICY IF EXISTS "Prompts Policy Delete" ON prompts_ia;
CREATE POLICY "Prompts Policy Delete" ON prompts_ia
FOR DELETE
USING (
  id_clinica IN (
    SELECT id_clinica FROM usuarios WHERE id = auth.uid()
  )
  AND (
    terapeuta_id = auth.uid()
    OR
    EXISTS (
      SELECT 1 FROM usuarios 
      WHERE id = auth.uid() 
      AND tipo_perfil != 'terapeuta'
    )
  )
);
