CREATE TABLE IF NOT EXISTS relatorios_atendimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_agendamento BIGINT REFERENCES agendamentos(id) ON DELETE CASCADE,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE,
    id_terapeuta UUID REFERENCES usuarios(id) ON DELETE CASCADE,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    texto_bruto TEXT,
    relatorio_gerado TEXT,
    id_prompt_ia BIGINT REFERENCES prompts_ia(id) ON DELETE SET NULL,
    status TEXT DEFAULT 'rascunho', -- 'rascunho', 'finalizado'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE relatorios_atendimento ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Relatorios Policy Select" ON relatorios_atendimento;
CREATE POLICY "Relatorios Policy Select" ON relatorios_atendimento
FOR SELECT
USING (
  id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
  AND (
    id_terapeuta = auth.uid()
    OR
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil != 'terapeuta')
  )
);

DROP POLICY IF EXISTS "Relatorios Policy Insert" ON relatorios_atendimento;
CREATE POLICY "Relatorios Policy Insert" ON relatorios_atendimento
FOR INSERT
WITH CHECK (
  id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
  AND (
    id_terapeuta = auth.uid()
    OR
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil != 'terapeuta')
  )
);

DROP POLICY IF EXISTS "Relatorios Policy Update" ON relatorios_atendimento;
CREATE POLICY "Relatorios Policy Update" ON relatorios_atendimento
FOR UPDATE
USING (
  id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
  AND (
    id_terapeuta = auth.uid()
    OR
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil != 'terapeuta')
  )
);

DROP POLICY IF EXISTS "Relatorios Policy Delete" ON relatorios_atendimento;
CREATE POLICY "Relatorios Policy Delete" ON relatorios_atendimento
FOR DELETE
USING (
  id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
  AND (
    id_terapeuta = auth.uid()
    OR
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil != 'terapeuta')
  )
);
