-- Create Help Desk Tables

CREATE TABLE IF NOT EXISTS help_desk_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Quem abriu e de onde
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    id_usuario_criador UUID REFERENCES usuarios(id) ON DELETE SET NULL,
    
    -- Dados do Ticket
    assunto TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('problema', 'sugestao', 'duvida', 'financeiro', 'outro')),
    prioridade TEXT DEFAULT 'media' CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
    status TEXT DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_andamento', 'aguardando_cliente', 'resolvido', 'fechado')),
    
    -- Controle
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS help_desk_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Vínculo
    id_ticket BIGINT REFERENCES help_desk_tickets(id) ON DELETE CASCADE,
    id_usuario UUID REFERENCES usuarios(id) ON DELETE SET NULL, -- Quem enviou a mensagem
    
    -- Conteúdo
    mensagem TEXT NOT NULL,
    anexo_url TEXT, -- Opcional: Para prints ou arquivos
    
    -- Controle
    lida BOOLEAN DEFAULT FALSE, -- Para marcar se você ou o cliente já leram
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_tickets_clinica ON help_desk_tickets(id_clinica);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON help_desk_tickets(status);
CREATE INDEX IF NOT EXISTS idx_mensagens_ticket ON help_desk_mensagens(id_ticket);

-- RLS Policies

ALTER TABLE help_desk_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE help_desk_mensagens ENABLE ROW LEVEL SECURITY;

-- Tickets Policies
DROP POLICY IF EXISTS "Tickets Select Policy" ON help_desk_tickets;
CREATE POLICY "Tickets Select Policy" ON help_desk_tickets
FOR SELECT
USING (
    -- Admin SaaS (id_clinica IS NULL) sees all
    (SELECT id_clinica FROM usuarios WHERE id = auth.uid()) IS NULL
    OR
    -- Clinic User sees only their clinic's tickets
    id_clinica = (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Tickets Insert Policy" ON help_desk_tickets;
CREATE POLICY "Tickets Insert Policy" ON help_desk_tickets
FOR INSERT
WITH CHECK (
    -- User can only create for their own clinic
    id_clinica = (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Tickets Update Policy" ON help_desk_tickets;
CREATE POLICY "Tickets Update Policy" ON help_desk_tickets
FOR UPDATE
USING (
    -- Admin SaaS can update any
    (SELECT id_clinica FROM usuarios WHERE id = auth.uid()) IS NULL
    OR
    -- Clinic User can update their own (e.g. close ticket)
    id_clinica = (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- Mensagens Policies
DROP POLICY IF EXISTS "Mensagens Select Policy" ON help_desk_mensagens;
CREATE POLICY "Mensagens Select Policy" ON help_desk_mensagens
FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM help_desk_tickets t
        WHERE t.id = help_desk_mensagens.id_ticket
        AND (
            -- Admin SaaS sees messages from any ticket
            (SELECT id_clinica FROM usuarios WHERE id = auth.uid()) IS NULL
            OR
            -- Clinic User sees messages from their clinic's tickets
            t.id_clinica = (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
        )
    )
);

DROP POLICY IF EXISTS "Mensagens Insert Policy" ON help_desk_mensagens;
CREATE POLICY "Mensagens Insert Policy" ON help_desk_mensagens
FOR INSERT
WITH CHECK (
    EXISTS (
        SELECT 1 FROM help_desk_tickets t
        WHERE t.id = help_desk_mensagens.id_ticket
        AND (
            -- Admin SaaS can reply to any
            (SELECT id_clinica FROM usuarios WHERE id = auth.uid()) IS NULL
            OR
            -- Clinic User can reply to their clinic's tickets
            t.id_clinica = (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
        )
    )
);
