-- Add 'recepcao' to allowed user profiles check constraint if it exists, or just ensure the app handles it.
-- Since Supabase check constraints are usually hardcoded in previous migrations, we might need to update it.
-- However, usually 'text' columns don't have strict ENUMs unless explicitly created.
-- Let's check if there is a constraint and update it if necessary.

-- Dropping the constraint if it exists to allow new values, then re-adding it with 'recepcao'
DO $$ 
BEGIN 
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'usuarios_tipo_perfil_check') THEN 
        ALTER TABLE usuarios DROP CONSTRAINT usuarios_tipo_perfil_check; 
    END IF; 
END $$;

ALTER TABLE usuarios 
ADD CONSTRAINT usuarios_tipo_perfil_check 
CHECK (tipo_perfil IN ('admin', 'terapeuta', 'recepcao'));

-- Create 'salas' table for room management
CREATE TABLE IF NOT EXISTS salas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT,
    capacidade INT DEFAULT 1,
    cor_identificacao TEXT DEFAULT '#3b82f6', -- Blue default
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for Salas
ALTER TABLE salas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Salas Select Policy" ON salas;
CREATE POLICY "Salas Select Policy" ON salas
FOR SELECT
USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

DROP POLICY IF EXISTS "Salas Insert Policy" ON salas;
CREATE POLICY "Salas Insert Policy" ON salas
FOR INSERT
WITH CHECK (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND 
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'recepcao'))
);

DROP POLICY IF EXISTS "Salas Update Policy" ON salas;
CREATE POLICY "Salas Update Policy" ON salas
FOR UPDATE
USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND 
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'recepcao'))
);

DROP POLICY IF EXISTS "Salas Delete Policy" ON salas;
CREATE POLICY "Salas Delete Policy" ON salas
FOR DELETE
USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND 
    EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil = 'admin') -- Only admin can delete
);
