-- Criação de tabelas para integração com Robô Tirilo

-- 1. Tabela de Frota de Robôs (Autorização)
CREATE TABLE IF NOT EXISTS saas_frota_robos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mac_address TEXT NOT NULL UNIQUE,
    nome_identificacao TEXT,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE SET NULL,
    status_bloqueio BOOLEAN DEFAULT TRUE,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabela de Configuração de IA por Clínica
CREATE TABLE IF NOT EXISTS clinica_config_ia (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE,
    prompt_personalidade_robo TEXT DEFAULT 'Você é o Tirilo, um robô amigo e terapêutico.',
    motor_voz_preferencial TEXT DEFAULT 'pt-br',
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_config_clinica UNIQUE (id_clinica)
);

-- 3. Tabela de Comandos para o Robô (Queue)
CREATE TABLE IF NOT EXISTS comandos_robo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE CASCADE,
    comando TEXT NOT NULL, -- ex: 'FALAR', 'JOGAR_CORES', 'PARAR'
    parametros JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'PENDENTE', -- 'PENDENTE', 'EXECUTADO', 'ERRO'
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    executado_em TIMESTAMPTZ
);

-- 4. Tabela de Telemetria/Logs da Sessão
CREATE TABLE IF NOT EXISTS sessao_telemetria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address TEXT REFERENCES saas_frota_robos(mac_address) ON DELETE SET NULL,
    jogo TEXT, -- qual jogo ou atividade
    resultado TEXT, -- 'venceu', 'perdeu', 'log'
    detalhes JSONB DEFAULT '{}'::jsonb, -- dados extras
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies (Simplificado para MVP/Admin)
ALTER TABLE saas_frota_robos ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinica_config_ia ENABLE ROW LEVEL SECURITY;
ALTER TABLE comandos_robo ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessao_telemetria ENABLE ROW LEVEL SECURITY;

-- Permitir leitura pública para robôs (via API Key/Anon se necessário, ou restringir depois)
-- Por enquanto, usaremos service_role ou anon key no robo, políticas focadas no admin do saas

-- Admin vê tudo
CREATE POLICY "Admin vê todas frotas" ON saas_frota_robos
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil = 'admin'));

CREATE POLICY "Admin vê configs" ON clinica_config_ia
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil = 'admin'));

CREATE POLICY "Admin gerencia comandos" ON comandos_robo
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil = 'admin'));

CREATE POLICY "Admin vê telemetria" ON sessao_telemetria
    FOR ALL USING (auth.uid() IN (SELECT id FROM usuarios WHERE tipo_perfil = 'admin'));

-- Robô (Anon/Service) precisa ler/escrever. 
-- Idealmente configurariamos um role postgres 'robot_role', mas para MVP via supabase-py client:
-- Se o robô usa 'service_role' key, ele ignora RLS.
-- Se usa 'anon' key, precisamos liberar:

CREATE POLICY "Robo le comandos" ON comandos_robo
    FOR SELECT USING (true); -- Refinar para mac_address depois se autenticado

CREATE POLICY "Robo atualiza comandos" ON comandos_robo
    FOR UPDATE USING (true);

CREATE POLICY "Robo insere telemetria" ON sessao_telemetria
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Robo le config" ON clinica_config_ia
    FOR SELECT USING (true);

CREATE POLICY "Robo verifica frota" ON saas_frota_robos
    FOR SELECT USING (true);
