-- Migration: Módulo Financeiro
-- Data: 07/12/2025
-- Descrição: Criação de tabelas e alterações para o módulo financeiro e perfil de usuário

-- 1. Alterar tabela USUARIOS para aceitar perfil 'financeiro'

-- 1.1 Remove a constraint existente PRIMEIRO.
-- Nota: Usamos IF EXISTS para evitar erros se a constraint tiver outro nome ou não existir,
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_tipo_perfil_check;

-- 1.2 Normalizar dados existentes (Correção de dados sujos)
-- Primeiro, limpa espaços e normaliza para minúsculas
UPDATE usuarios SET tipo_perfil = LOWER(TRIM(tipo_perfil));

-- Atualiza QUALQUER perfil que ainda não esteja na lista permitida para 'admin'
UPDATE usuarios 
SET tipo_perfil = 'admin' 
WHERE tipo_perfil NOT IN ('admin', 'terapeuta', 'recepcao', 'financeiro');

-- 1.3 Recria a constraint com as novas permissões
ALTER TABLE usuarios ADD CONSTRAINT usuarios_tipo_perfil_check 
CHECK (tipo_perfil IN ('admin', 'terapeuta', 'recepcao', 'financeiro'));

-- 2. Alterar tabela TERAPEUTAS_CURRICULO para incluir valores
ALTER TABLE terapeutas_curriculo 
ADD COLUMN IF NOT EXISTS valor_hora_padrao DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS porcentagem_repasse DECIMAL(5,2);

-- 3. Alterar tabela PACIENTES (Campos fallback)
ALTER TABLE pacientes 
ADD COLUMN IF NOT EXISTS valor_sessao_padrao DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS dia_vencimento_padrao INTEGER,
ADD COLUMN IF NOT EXISTS convenio_nome TEXT,
ADD COLUMN IF NOT EXISTS convenio_numero_carteirinha TEXT,
ADD COLUMN IF NOT EXISTS convenio_validade DATE;

-- 4. Criar tabela CONTRATOS
CREATE TABLE IF NOT EXISTS contratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE CASCADE NOT NULL,
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE CASCADE NOT NULL,
    tipo_cobranca TEXT NOT NULL CHECK (tipo_cobranca IN ('por_sessao', 'mensal_fixo')),
    valor DECIMAL(10,2) NOT NULL, -- Valor da sessão ou valor mensal
    data_inicio DATE NOT NULL,
    data_fim DATE,
    dia_vencimento INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'ativo' CHECK (status IN ('ativo', 'cancelado', 'finalizado')),
    arquivo_url TEXT, -- URL do PDF no bucket
    observacoes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Contratos
ALTER TABLE contratos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to contracts" ON contratos
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND (
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'financeiro'))
    )
);

-- 5. Criar tabela FINANCEIRO_CATEGORIAS
CREATE TABLE IF NOT EXISTS financeiro_categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    nome TEXT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Categorias
ALTER TABLE financeiro_categorias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to financial categories" ON financeiro_categorias
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
);

-- 6. Criar tabela FINANCEIRO_LANCAMENTOS
CREATE TABLE IF NOT EXISTS financeiro_lancamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clinica BIGINT REFERENCES saas_clinicas(id) ON DELETE CASCADE NOT NULL,
    descricao TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE,
    status TEXT DEFAULT 'pendente' CHECK (status IN ('pendente', 'pago', 'cancelado')),
    tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
    id_paciente BIGINT REFERENCES pacientes(id) ON DELETE SET NULL,
    id_responsavel BIGINT REFERENCES responsaveis(id) ON DELETE SET NULL,
    id_categoria BIGINT REFERENCES financeiro_categorias(id) ON DELETE SET NULL,
    forma_pagamento TEXT CHECK (forma_pagamento IN ('pix', 'boleto', 'cartao', 'dinheiro', 'transferencia', 'outros')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Lançamentos
ALTER TABLE financeiro_lancamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Access to financial records" ON financeiro_lancamentos
FOR ALL USING (
    id_clinica IN (SELECT id_clinica FROM usuarios WHERE id = auth.uid())
    AND (
        EXISTS (SELECT 1 FROM usuarios WHERE id = auth.uid() AND tipo_perfil IN ('admin', 'financeiro'))
    )
);

-- 7. Alterar tabela AGENDAMENTOS para vincular ao financeiro
ALTER TABLE agendamentos 
ADD COLUMN IF NOT EXISTS id_lancamento_financeiro BIGINT REFERENCES financeiro_lancamentos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS valor_sessao DECIMAL(10,2);

-- Índices novos
CREATE INDEX IF NOT EXISTS idx_contratos_paciente ON contratos(id_paciente);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_clinica ON financeiro_lancamentos(id_clinica);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_vencimento ON financeiro_lancamentos(data_vencimento);
CREATE INDEX IF NOT EXISTS idx_financeiro_lancamentos_status ON financeiro_lancamentos(status);
